'use strict';
const D=window.DATA,G=window.Game,KEY='manma-trpg-v11';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=G.empty(),history=[],route='sheet',draft=null,step=1,gmOpen=false,lastRoll=null,storageError='',search='',ruleFilter='player',rollPreset='';
try{const raw=localStorage.getItem(KEY);if(raw)state=G.validateState(JSON.parse(raw),D);}catch(e){storageError='저장 기록을 읽지 못했습니다. 백업 화면에서 원본을 내려받은 뒤 복구해주세요.';}
const hero=()=>state.heroes.find(h=>h.id===state.activeId),job=h=>D.jobs[h.job],race=h=>D.races.find(r=>r.id===h.race),money=x=>Number(x).toLocaleString('ko-KR');
function useAbility(h,a,combat=true,override=false){return G.use(h,a,combat,override,state.party.marathon?3:1);}
function usageLabel(h,a){return `${a.period==='session'&&state.party.marathon?'정주행 전체':periodName(a.period)} ${Math.max(0,G.usageLimit(a,state.party.marathon?3:1)-G.usageCount(h,a))}/${G.usageLimit(a,state.party.marathon?3:1)}회 남음`;}
function requiresRoll(a){return /판정|공격/.test(a.description)&&!a.description.includes('판정 없')&&a.name!=='드론 조종';}
function rollChoices(h){return [...D.skills.map(k=>k.name),...(h.job===1?['기본 마도 화살']:h.job===2?['기본 신성탄']:[]),...job(h).skills.filter(a=>a.level<=h.level&&requiresRoll(a)).map(a=>'직업 · '+a.name)];}
const options=(arr,val)=>arr.map(x=>{let v=typeof x==='object'?x.value:x,l=typeof x==='object'?x.label:x;return `<option value="${esc(v)}" ${String(v)===String(val)?'selected':''}>${esc(l)}</option>`;}).join('');
const btn=(label,action,attrs='',cls='')=>`<button type="button" class="${cls}" data-action="${action}" ${attrs}>${label}</button>`;
const input=(name,label,value='',type='text',extra='')=>`<label class="field">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const select=(name,label,arr,val)=>`<label class="field">${label}<select name="${name}">${options(arr,val)}</select></label>`;
const head=(eyebrow,title,desc,actions='')=>`<div class="page-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p class="muted">${desc}</p></div><div class="actions">${actions}</div></div>`;
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4300);}
function persist(){if(storageError){$('#save-status').textContent='저장 보류';return;}try{localStorage.setItem(KEY,JSON.stringify(state));$('#save-status').textContent='이 기기에 저장됨';}catch(e){$('#save-status').textContent='저장 실패';toast('저장 공간을 사용할 수 없습니다. 백업을 다운로드해주세요.');}}
function change(fn,text){let old=JSON.stringify(state);try{fn();state.logs.unshift({time:new Date().toISOString(),text});state.logs=state.logs.slice(0,100);history.push(old);if(history.length>30)history.shift();persist();render();return true;}catch(e){state=JSON.parse(old);if($('#modal').open)closeModal();toast(e.message);return false;}}
function modal(title,html){$('#modal-title').textContent=title;$('#modal-body').innerHTML=html;if(!$('#modal').open)$('#modal').showModal();}
function closeModal(){$('#modal').close();}
function confirmAction(title,text,callback){modal(title,`<p>${esc(text)}</p><div class="actions"><button class="primary" id="confirm-yes" type="button">확인</button>${btn('취소','close')}</div>`);$('#confirm-yes').onclick=()=>{closeModal();callback();};}
function download(name,obj,mime='application/json'){let blob=new Blob([typeof obj==='string'?obj:JSON.stringify(obj,null,2)],{type:mime+';charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function navTo(v){location.hash=v;}
const navigation=[['sheet','내 캐릭터'],['create','캐릭터 생성'],['roll','판정 계산'],['rules','규칙 찾기'],['party','파티 현황'],['gm','GM 도구'],['backup','백업·기록']];
function render(){route=location.hash.slice(1)||'sheet';if(!navigation.some(x=>x[0]===route))route='sheet';$('#nav').innerHTML=navigation.map(([id,label],i)=>`<a href="#${id}" class="${route===id?'active':''}" ${route===id?'aria-current="page"':''}><span class="nav-num">0${i+1}</span>${label}</a>`).join('');const views={sheet:renderSheet,create:renderCreate,roll:renderRoll,rules:renderRules,party:renderParty,gm:renderGM,backup:renderBackup};$('#main').innerHTML=(storageError?`<div class="notice warning">${esc(storageError)} <a href="#backup">복구 화면</a></div>`:'')+views[route]();if(route==='rules')drawRules();if(route==='roll')setupRoll();if(route==='create')refreshCreation();}
function absent(){return `<div class="card empty"><h2>먼저 캐릭터를 만들어주세요.</h2><p class="muted">종족 20종, 직업 6종 중에서 이번 모험의 주인공을 고르세요.</p><div class="actions"><a href="#create">캐릭터 만들기</a><a href="#backup">기존 캐릭터 불러오기</a></div></div>`;}
function renderSheet(){let h=hero();if(!h)return head('PLAYER DESK','이번 모험의 주인공','캐릭터를 만들거나 이전 기록을 불러오세요.')+`<div class="intro-empty">${absent()}<div class="grid two"><div class="card"><span class="pill green">준비물</span><h2>D20 두 개, D6 두 개</h2><p class="muted">실물 주사위를 굴린 뒤 눈을 입력하면 판정값을 계산합니다.</p><a href="#rules">플레이 규칙 읽기</a></div><div class="card"><span class="pill blue">GM 1명 + 플레이어 4명</span><h2>파티를 이끌어주세요</h2><p class="muted">적 체력, 전투 차례, 공용 골드와 단서를 관리합니다.</p><a href="#gm">GM 도구 열기</a></div></div></div>`;
let max=G.maximum(h,D),j=job(h),r=race(h);
return head('PLAYER DESK','내 캐릭터','이번 턴에 할 일을 고르고, 결과를 기록하세요.',`<select class="hero-pick" id="hero-pick" aria-label="캐릭터 선택">${options(state.heroes.map(x=>({value:x.id,label:x.name})),h.id)}</select>${btn('인쇄','print','','quiet')}`)+
`<div class="wide-split"><section><div class="card"><div class="identity"><div class="avatar">${esc(h.name.slice(0,1))}</div><div><h2>${esc(h.name)}</h2><span class="pill green">Lv.${h.level} ${j.name}</span><span class="pill">${r.name}</span><span class="pill">${D.origins[h.origin].name}</span><span class="pill">${esc(h.gender||'성별 미정')}</span></div></div><div class="stats">${G.STATS.map(k=>`<div class="stat"><span>${k}</span><strong>${h.stats[k]}</strong></div>`).join('')}<div class="stat"><span>방어도</span><strong>${G.defense(h)}</strong></div></div></div>
<div class="grid three">${resource('hp','체력',h.hp,max,'피해·회복', 'health')}${resource('focus','집중',h.focus,G.focusMax(h))}${resource('luck','행운',h.luck,2)}</div>
<div class="section-head"><h2>이번 턴</h2><span class="pill ${h.attacked?'pink':'green'}">공격 ${h.attacked?'사용 완료':'사용 가능'}</span></div><div class="card"><div class="actions"><span class="pill blue">행동력 ${h.ap} / 2</span>${btn('기본 공격','basic')}${btn('방어','defend')}${btn('이동','move')}${btn('도움','assist')}${h.job===5?btn(h.mode+' → 모드 전환','mode'):''}</div><div class="quick-actions">${btn('내 턴 시작','turn','','quiet small')}${btn('새 전투','battle-reset','','quiet small')}${btn('GM 수동 수정','edit-resources','','quiet small')}${btn('직전 조작 취소','undo','','quiet small')}</div><p class="small-text">기술 사용은 비용과 횟수를 기록합니다. 명중·피해·대상 효과는 주사위 판정 후 별도로 반영하세요.</p></div>
<div class="section-head"><h2>사용 가능한 기술</h2><span class="small-text">${j.skills.filter(s=>s.level<=h.level).length}개 해금</span></div><div class="grid two">${j.skills.map(a=>`<article class="card skill ${a.level>h.level?'disabled':''}"><div><span class="pill">${a.level}단계</span>${a.attack?'<span class="pill pink">공격 행동</span>':''}${a.period?`<span class="pill">${usageLabel(h,a)}</span>`:''}</div><h3>${a.name}</h3><small>행동력 ${a.ap} · 집중 ${a.focus}${a.gold?' · '+a.gold+'G':''}</small><p>${esc(a.description)}</p><div class="actions">${btn(a.level>h.level?'레벨 '+a.level+'에 해금':'사용 기록','skill',`data-id="${a.id}" ${a.level>h.level?'disabled':''}`)}${a.level<=h.level&&requiresRoll(a)?btn('판정 계산','skill-roll',`data-id="${a.id}"`,'quiet'):''}</div></article>`).join('')}</div></section>
<aside><div class="card"><div class="eyebrow">SPECIES / ${String(r.id).padStart(2,'0')}</div><h2>${r.name}</h2><p>${esc(r.trait)}</p>${r.period==='passive'?'<span class="pill green">상시 특성</span>':btn(usageLabel(h,{...r,id:'race'})+' · 기록','race','','quiet')}<a class="small-text" href="#rules"> 상세 범위는 종족 규칙에서 확인</a></div>
<div class="card"><h2>상태와 보호막</h2><div class="counter"><span>보호막</span><strong class="value">${h.shield}</strong>${btn('수정','shield','','small')}</div>${h.hp===0?`<div class="notice warning">전투 불능 · 위기 ${h.crisis}/3 ${h.stable?'· 안정화':''}${h.injured?'· 중상':''}<div class="actions">${btn('위기 D6 입력','crisis','','small')}${btn('안정화 기록','stabilize','','small')}</div></div>`:''}<div>${h.statuses.map((x,i)=>`<div class="status-item"><div><strong>${esc(x.name)}</strong><small><br>${esc(x.source||'부여자 미기록')} · ${esc(x.until||'종료 시점 미기록')}</small></div>${btn('해제','status-remove',`data-i="${i}"`,'small quiet')}</div>`).join('')||'<p class="muted">상태 이상 없음</p>'}</div>${btn('+ 상태 추가','status-add','','quiet')}</div>
<div class="card"><h2>직업 특성</h2><p class="small-text">${esc(D.rules.find(x=>x.id===h.job+5).text.split('### 특성과')[1]?.split('### 1단계')[0]?.replace(/^[^\n]+\n/,'').trim()||'직업 규칙을 확인하세요.')}</p></div><div class="card"><h2>정비와 성장</h2><div class="actions">${btn('짧은 휴식','short-rest')}${btn('긴 휴식','long-rest')}${btn('레벨 업','level',h.level>=3?'disabled':'')}</div><p class="inline-note">휴식은 GM이 허용한 안전한 장소에서 진행하세요.</p><h3>숙련</h3><p>${h.trained.map(x=>`<span class="pill">${esc(x)} +2</span>`).join(' ')}</p></div>
<div class="card"><div class="section-head" style="margin-top:0"><h2>장비</h2><span class="pill">${G.slots(h)} / 4칸</span></div><p>${esc(h.weapon)} · ${h.armor==='heavy'?'중갑':'경갑'}</p><p><strong>${money(h.gold)} G</strong></p>${h.inventory.map(i=>{let item=D.items.find(x=>x.id===i.item);return `<div class="catalog-row"><div><strong>${item.name}</strong><small><br>${i.slots}칸 ${i.free?'· 지급품':''}</small></div>${btn('사용','item',`data-id="${i.id}"`,'small')}</div>`;}).join('')}<div class="quick-actions">${btn('상점·장비 관리','shop','','quiet')}${btn('캐릭터 내보내기','export-hero','','quiet')}</div></div>
<div class="card"><h2>나의 이야기</h2><h3>외형</h3><p class="muted">${esc(h.appearance||'아직 기록하지 않았습니다.')}</p><h3>의뢰를 받는 이유</h3><p>${esc(h.goal||'미정')}</p><h3>동료와의 관계</h3><p>${esc(h.bond||'미정')}</p>${h.job===2?'<h3>서약</h3><p>'+esc(h.oath)+'</p>':''}${btn('설정 수정','edit-story','','quiet')}</div></aside></div>`;
}
function resource(key,label,val,max,actionLabel,action){return `<div class="card resource ${key}"><div class="label">${label}</div><div class="value">${val} <small>/ ${max}</small></div><div class="meter"><span style="width:${max?Math.min(100,val/max*100):0}%"></span></div>${action?btn(actionLabel,action,'','small'): `<div class="counter">${btn('−','resource',`data-key="${key}" data-delta="-1" aria-label="${label} 1 감소"`,'small')}<span class="small-text">1씩 조정</span>${btn('+','resource',`data-key="${key}" data-delta="1" aria-label="${label} 1 증가"`,'small')}</div>`}</div>`;}
function periodName(p){return {battle:'전투당',session:'모임당',scene:'장면당',rest:'긴 휴식당',expedition:'진입당'}[p]||'';}
function initDraft(){draft={name:'',gender:'',appearance:'',goal:'',bond:'',oath:'약속의 대가를 속이지 않는다',race:1,job:0,origin:0,originChoice:'자물쇠 따기',stats:{근력:3,민첩:2,지능:0,감각:1,의지:1},trained:[],weapon:'총기'};step=1;}
function readDraft(){let f=$('#creator');if(!f)return;let v=new FormData(f);if(step===1){for(let k of ['name','gender','appearance','goal','bond','oath'])if(v.has(k))draft[k]=String(v.get(k));for(let k of ['race','job','origin'])draft[k]=Number(v.get(k));let o=D.origins[draft.origin];if(!o.choice.includes(draft.originChoice))draft.originChoice=o.choice[0]||'';}if(step===2){G.STATS.forEach(k=>draft.stats[k]=Number(v.get(k)));draft.originChoice=String(v.get('originChoice')||'');draft.trained=v.getAll('trained');}if(step===3)draft.weapon=String(v.get('weapon')||'총기');}
function renderCreate(){if(!draft)initDraft();let d=draft;return head('CHARACTER CREATOR','새 캐릭터 만들기','선택은 자유롭게. 종족과 성별은 능력치를 바꾸지 않습니다.')+`<div class="steps">${['정체성과 배경','능력치와 숙련','최종 확인'].map((x,i)=>`<div class="step ${step===i+1?'current':step>i+1?'done':''}">0${i+1} ${x}</div>`).join('')}</div><form id="creator" class="card"><div class="form-grid">${step===1?`
${input('name','이름',d.name,'text','maxlength="60" required')}${input('gender','성별·호칭',d.gender,'text','maxlength="80" placeholder="자유롭게 입력 또는 미정"')}
${select('race','종족',D.races.map(r=>({value:r.id,label:String(r.id).padStart(2,'0')+' · '+r.name})),d.race)}${select('job','직업',D.jobs.map((j,i)=>({value:i,label:j.name})),d.job)}
${select('origin','출신',D.origins.map((o,i)=>({value:i,label:o.name})),d.origin)}<div class="field"><span>주사위로 고르기</span><div class="actions">${btn('종족 D20 × 2','random-race')}${btn('직업 D6','random-job')}${btn('출신 D3','random-origin')}</div></div>
<div class="field full"><div id="creation-info" class="notice"></div></div>${input('appearance','외형·나이',d.appearance,'text','maxlength="500"')}${input('goal','의뢰를 받는 이유',d.goal,'text','maxlength="500"')}${input('bond','동료와의 관계',d.bond,'text','maxlength="500"')}${input('oath','성기사라면 지킬 서약',d.oath,'text','maxlength="300"')}`:step===2?`
<div class="field full"><h2>3, 2, 1, 1, 0을 하나씩 배치하세요</h2><p class="muted">${esc(D.jobs[d.job].description)}</p></div>${G.STATS.map(k=>select(k,k,[0,1,2,3],d.stats[k])).join('')}
<div class="field full"><h3>출신 숙련</h3><p>${esc(D.origins[d.origin].description)}</p>${D.origins[d.origin].choice.length?select('originChoice','하나 선택',D.origins[d.origin].choice,d.originChoice):''}<h3>추가 공통 숙련 4개</h3><p class="small-text">출신으로 얻는 숙련과 중복 선택할 수 없습니다.</p><div class="checks">${D.skills.map(k=>`<label class="check"><input type="checkbox" name="trained" value="${k.name}" ${d.trained.includes(k.name)?'checked':''}>${k.name}<small>${k.stat}</small></label>`).join('')}</div></div>`:`
<div class="field full"><h2>${esc(d.name)} <span class="pill green">${D.races.find(r=>r.id===d.race).name} · ${D.jobs[d.job].name}</span></h2><p>${esc(d.gender||'성별 미정')} · ${D.origins[d.origin].name}</p><div class="stats">${G.STATS.map(k=>`<div class="stat"><span>${k}</span><strong>${d.stats[k]}</strong></div>`).join('')}</div><div class="notice">시작 체력 ${D.jobs[d.job].hp+d.stats['근력']*2} · 방어도 ${11+d.stats['민첩']} · 집중 3 · 행운 2 · ${30+D.origins[d.origin].gold}G</div><p>공통 숙련: ${esc(d.trained.join(', '))}<br>출신 숙련: ${esc([...D.origins[d.origin].skills,...(d.originChoice?[d.originChoice]:[])].join(', '))}</p></div>${select('weapon','기본 무기',['총기','근접 무기'],d.weapon)}<div class="field"><span>기본 지급 장비</span><p>경갑 · 통신기 · 직업 도구<br>회복약 1개 · 만능 공구 1개${d.race===5?'<br>고블린 전용 공구 1개 추가':''}${d.job===4?'<br>방랑상인 비상 섬광탄 1개':''}</p></div>`}</div><hr class="divider"><div class="actions">${step>1?btn('이전','create-prev'):''}${step<3?btn('다음 단계','create-next','','primary'):'<button class="primary" type="submit">이 캐릭터로 시작</button>'}${btn('입력 초기화','create-reset','','quiet')}</div></form>`;}
function refreshCreation(){if(step!==1)return;let f=$('#creator');const update=()=>{readDraft();let d=draft,r=D.races.find(x=>x.id===d.race);$('#creation-info').innerHTML=`<strong>${r.name}</strong> · ${esc(r.lore)}<br>${esc(r.trait)}<hr class="divider"><strong>${D.jobs[d.job].name}</strong> · 기본 체력 ${D.jobs[d.job].hp}<br>${esc(D.origins[d.origin].description)}`;};f.querySelectorAll('select').forEach(x=>x.addEventListener('change',update));update();}
function renderRoll(){let h=hero();return head('DICE CHECK','판정 계산','실물 주사위 눈을 입력하세요. 피해 주사위는 별도로 굴립니다.')+(h?`<div class="wide-split"><form id="roll-form" class="card"><h2>${esc(h.name)}의 판정</h2><div class="form-grid">${select('skill','행동',rollChoices(h),rollPreset||'사격')}${select('stat','사용 능력치',G.STATS,'민첩')}${select('mode','유리·불리',[{value:'normal',label:'일반 · D20 1개'},{value:'advantage',label:'유리 · 높은 눈'},{value:'disadvantage',label:'불리 · 낮은 눈'}],'normal')}${input('dc','목표치 / 적 방어도',12,'number','min="1" max="99" required')}${input('die','첫 번째 D20 눈','','number','min="1" max="20" required')}${input('die2','두 번째 D20 눈','','number','min="1" max="20" disabled')}${input('modifier','상황 보정 합계',0,'number','min="-2" max="2" required')}<div class="field"><span>판정 종류</span><label class="switch-line"><input type="checkbox" name="trained" checked>숙련 +2</label><label class="switch-line"><input type="checkbox" name="attack">공격 판정 · 1 실패 / 20 치명타</label></div></div><p class="inline-note">자동으로 선택한 능력치·숙련은 GM 판단에 따라 바꿀 수 있습니다.</p><button type="submit" class="primary">결과 계산·기록</button><div id="roll-result"></div></form><div><div class="card"><h2>판정 공식</h2><p>D20 + 능력치 + 숙련 + 상황 보정</p><p class="muted">목표치 이상이면 성공합니다. 상황 보정은 합계 -2~+2입니다. 유리와 불리가 동시에 있으면 일반 판정으로 처리하세요.</p><div class="table-scroll"><table><tr><th>난도</th><th>목표치</th></tr><tr><td>쉬움</td><td>10</td></tr><tr><td>보통</td><td>12</td></tr><tr><td>어려움</td><td>15</td></tr><tr><td>매우 어려움</td><td>18</td></tr></table></div></div><div class="card"><h2>행운으로 재굴림</h2><p class="muted">판정당 한 번만 가능합니다. 유리·불리면 두 주사위를 모두 다시 굴려주세요. 재굴림은 새 결과를 사용합니다.</p>${btn('행운 1 지불 후 재입력','reroll',(!lastRoll||lastRoll.retried||h.luck<1||lastRoll.heroId!==h.id)?'disabled':'')}</div></div></div>`:absent());}
function setupRoll(){let f=$('#roll-form');if(!f)return;const sync=()=>{let h=hero(),name=f.elements.skill.value,s=D.skills.find(x=>x.name===name),a=job(h).skills.find(x=>'직업 · '+x.name===name);let stat=s?s.stat:a?(h.job===0&&['강타','제압 공격','연속 타격'].includes(a.name)?(h.weapon==='총기'?'민첩':'근력'):a.stat):h.job===2?'의지':'지능';f.elements.stat.value=stat;f.elements.trained.checked=s?h.trained.includes(s.name):true;f.elements.attack.checked=s?['사격','근접 타격'].includes(s.name):a?!!a.attack:true;if(s?.name==='은신'&&h.armor==='heavy'){f.elements.mode.value='disadvantage';f.elements.die2.disabled=false;f.elements.die2.required=true;}};f.elements.skill.onchange=sync;f.elements.mode.onchange=()=>{f.elements.die2.disabled=f.elements.mode.value==='normal';f.elements.die2.required=f.elements.mode.value!=='normal';};sync();rollPreset='';if(lastRoll&&lastRoll.heroId===hero().id){if(lastRoll.pending){let r=lastRoll;f.elements.skill.value=r.skill;f.elements.stat.value=r.statName;f.elements.mode.value=r.params.mode;f.elements.mode.onchange();f.elements.trained.checked=r.params.trained;f.elements.modifier.value=r.params.modifier;f.elements.dc.value=r.params.dc;f.elements.attack.checked=r.params.attack;}showRoll();}}
function showRoll(){if(!$('#roll-result')||!lastRoll)return;let r=lastRoll.result;$('#roll-result').innerHTML=`<div class="result-card ${r.success?'':'fail'}"><span class="pill ${r.success?'green':'pink'}">${r.critical?'치명타':r.success?'성공':'실패'}${lastRoll.retried?' · 재굴림':''}</span><div class="result-number">${r.total}</div><p>D20 ${r.face} + 능력치 ${lastRoll.params.stat} + 숙련 ${lastRoll.params.trained?2:0} + 상황 ${lastRoll.params.modifier} · 목표치 ${lastRoll.params.dc}</p><small>${lastRoll.skill} · 비용·체력은 자동 변경하지 않습니다.</small></div>`;}
function markdown(txt){let lines=txt.split('\n'),out=[],i=0;while(i<lines.length){let line=lines[i];if(line.startsWith('|')){let rows=[];while(i<lines.length&&lines[i].startsWith('|')){if(!/^\|[-\s|]+\|$/.test(lines[i]))rows.push(lines[i].slice(1,-1).split('|'));i++;}out.push('<div class="table-scroll"><table>'+rows.map((r,j)=>'<tr>'+r.map(c=>`<${j?'td':'th'}>${esc(c)}</${j?'td':'th'}>`).join('')+'</tr>').join('')+'</table></div>');continue;}if(line.startsWith('### '))out.push('<h3>'+esc(line.slice(4))+'</h3>');else if(line.trim())out.push('<p>'+esc(line)+'</p>');i++;}return out.join('');}
function renderRules(){return head('RULEBOOK / V1.1','규칙 찾기','종족 20종 · 직업 6종 · 원문 수록')+`<div class="toolbar"><label class="field">검색<input id="rule-search" value="${esc(search)}" placeholder="예: 기절, 악마, 귀환" type="search"></label><label class="field">범위<select id="rule-filter">${options([{value:'player',label:'플레이어 규칙'},{value:'gm',label:'GM 규칙 · 스포일러'}],ruleFilter)}</select></label></div><p id="rule-count" class="small-text"></p><div id="rule-results" class="rules-list"></div>`;}
function drawRules(){let query=search.trim().toLowerCase();let rs=D.rules.filter(r=>(ruleFilter==='gm'?r.gm:!r.gm)&&(!query||(r.title+' '+r.text).toLowerCase().includes(query)));$('#rule-count').textContent=rs.length+'개 장';$('#rule-results').innerHTML=rs.map(r=>`<details ${query?'open':''}><summary>${esc(r.title)}</summary><div class="rule-body">${markdown(r.text)}</div></details>`).join('')||'<div class="card">검색 결과가 없습니다. 다른 단어를 입력해보세요.</div>';}
function renderParty(){let p=state.party;return head('PARTY RECORD','파티 현황','기록 담당자의 기기에서 공용 자원을 관리하세요.',btn('다음 진입','next-expedition','','primary'))+`<div class="grid four"><div class="card resource"><div class="label">공용 골드</div><div class="value">${money(p.gold)} <small>G</small></div>${btn('입출금','party-money',`data-key="gold"`,'quiet small')}</div><div class="card resource"><div class="label">부채</div><div class="value">${money(p.debt)} <small>G</small></div>${btn('차입·상환','debt','','quiet small')}</div><div class="card resource"><div class="label">진입 / 경계 단계</div><div class="value">${p.expedition} <small>/ 3</small></div><small>재진입할수록 보스 강화</small></div><div class="card resource"><div class="label">AI 신뢰</div><div class="counter">${btn('−','trust','data-delta="-1"','small')}<strong class="value">${p.trust}</strong>${btn('+','trust','data-delta="1"','small')}</div><small>장면당 최대 한 번 변경</small></div></div>
<div class="section-head"><h2>같은 기기의 캐릭터</h2><a href="#backup">다른 플레이어 파일 가져오기</a></div><div class="grid three">${state.heroes.map(h=>`<div class="card"><h3>${esc(h.name)}</h3><p>${race(h).name} · Lv.${h.level} ${job(h).name}</p><p>체력 ${h.hp}/${G.maximum(h,D)} · 집중 ${h.focus}/${G.focusMax(h)}</p>${btn('시트 열기','select-hero',`data-id="${h.id}"`,'quiet')}</div>`).join('')||'<p class="muted">등록된 캐릭터가 없습니다.</p>'}</div>
<div class="grid two" style="margin-top:24px"><div class="card"><div class="section-head" style="margin-top:0"><h2>전리품 배낭</h2><span class="pill">${p.loot.length} / 6칸</span></div>${p.loot.map((x,i)=>`<div class="catalog-row"><div><strong>${esc(x.name)}</strong><small><br>매각가 ${money(x.value)}G</small></div><div class="actions">${btn('판매','sell-loot',`data-i="${i}"`,'small')}${btn('버리기','discard-loot',`data-i="${i}"`,'small quiet')}</div></div>`).join('')||'<p class="muted">아직 획득한 전리품이 없습니다.</p>'}<div class="quick-actions">${btn('상자 열기','chest')}${btn('직접 추가','loot-add','','quiet')}</div><small>상자 보상은 판매 전까지 전투에서 사용할 수 없습니다.</small></div><div class="card"><h2>획득한 단서</h2>${['AI 비자금 인증 정보','불법 실험 사본','특수부대장 협조','봉쇄 해제 키'].map(c=>`<label class="check" style="margin-bottom:8px"><input type="checkbox" data-clue="${c}" ${p.clues.includes(c)?'checked':''}>${c}</label>`).join('')}<form id="notes-form"><label class="field">파티 메모<textarea name="notes" maxlength="10000">${esc(p.notes)}</textarea></label><button type="submit" class="quiet" style="margin-top:10px">메모 저장</button></form></div></div><p class="footnote">여러 기기의 기록은 자동 합쳐지지 않습니다. 전체 백업을 옮기면 해당 파일의 상태로 교체됩니다.</p>`;}
function actorHP(a){let h=state.heroes.find(h=>h.id===a.heroId);return a.type==='pc'&&h?{hp:h.hp,max:G.maximum(h,D),ac:G.defense(h)}:{hp:a.hp,max:a.max,ac:a.ac};}
function renderGM(){if(!gmOpen)return head('GAME MASTER','GM 진행 도구','전투와 시나리오를 진행하는 사람을 위한 화면입니다.')+`<div class="card"><h2>GM 정보와 스포일러가 포함되어 있습니다</h2><p class="muted">이 화면은 비밀번호로 보호되지 않습니다. 공개 페이지이므로 비밀 정보 보관용으로 사용하지 마세요.</p>${btn('GM 화면 열기','gm-open','','primary')}</div>`;let c=state.combat,current=c.actors[c.index];return head('GAME MASTER','전투 진행','참가자를 등록하고 우선권을 입력한 뒤 전투를 시작하세요.',`${btn('새 전투 준비','combat-clear','','quiet')}${btn('모임 시작','session-reset','','quiet')}`)+
`<div class="grid two"><div class="card"><h2>라운드 ${c.round}</h2><p class="result-number" style="font-size:30px">${c.running&&current?esc(current.name):'전투 준비'}</p><div class="actions">${!c.running?btn('전투 시작','combat-start',c.actors.length?'':'disabled','primary'):btn('다음 턴','combat-next','','primary')}${btn('전투 종료','combat-end',c.running?'':'disabled')}${btn('직전 조작 취소','undo','','quiet')}</div><p class="inline-note">현재 차례가 끝나면 출혈 피해를 적용하고 다음 플레이어의 행동력을 초기화합니다. 그 밖의 상태 종료는 수동으로 확인하세요.</p></div><div class="card"><h2>참가자 추가</h2><div class="actions">${btn('플레이어 추가','actor-pc',c.running?'disabled':'')}${btn('적 추가','actor-enemy',c.running?'disabled':'')}${btn('예고 패턴 확인','pattern')}</div><p class="inline-note">우선권: 플레이어 D20+민첩 · 적 D20+2<br>경계 ${state.party.expedition} · 일반 참가 인원 ${state.heroes.length||4}명 기준</p></div></div>
<div class="section-head"><h2>전투 순서</h2><span class="small-text">${c.actors.length}명</span></div>${c.actors.map((a,i)=>{let hp=actorHP(a);return `<div class="turn-row ${c.running&&i===c.index?'current':''}"><span class="init">${a.init}</span><div class="name"><strong>${esc(a.name)}</strong><small>${a.type==='pc'?'플레이어':'적'} · 방어도 ${hp.ac}${a.type==='enemy'?' · 명중 +'+a.bonus+' · 피해 '+a.damage:''}</small></div><span>체력 ${hp.hp} / ${hp.max}</span>${btn('체력 수정','actor-hp',`data-id="${a.id}"`,'small')}${btn('우선권','actor-init',`data-id="${a.id}" ${c.running?'disabled':''}`,'small quiet')}${btn('제외','actor-remove',`data-id="${a.id}" ${c.running?'disabled':''}`,'small quiet')}</div>`;}).join('')||'<div class="card muted">플레이어와 적을 추가해주세요.</div>'}
<div class="section-head"><h2>장면 관리</h2></div><div class="card"><div class="actions">${btn('새 탐색 장면','scene-reset')}${btn(state.party.marathon?'정주행 적용 중 · 각 3회':'정주행 규칙 적용','marathon-enable',state.party.marathon?'disabled':'')}</div><p class="inline-note">정주행에서는 모임당 1회 능력을 각각 총 3회 사용합니다. 기존 소비 횟수는 유지하며 휴식·층 이동으로 초기화하지 않습니다. 출신 특성과 AI 지원 횟수는 파티 메모에 직접 기록하세요. 행운은 기본 2개입니다.</p></div><div class="section-head"><h2>GM 규칙</h2><a href="#rules" data-action="gm-rules">전체 검색</a></div><div class="rules-list">${D.rules.filter(r=>r.gm).map(r=>`<details><summary>${esc(r.title)}</summary><div class="rule-body">${markdown(r.text)}</div></details>`).join('')}</div>`;}
function renderBackup(){return head('SAVE & RESTORE','백업과 기록','기기를 바꾸기 전, 기록을 파일로 보관하세요.')+`<div class="grid two"><div class="card"><h2>내보내기</h2><p class="muted">전체 백업에는 모든 캐릭터·파티·전투·로그가 포함됩니다.</p><div class="actions">${btn('전체 백업 다운로드','export-all','','primary')}${btn('현재 캐릭터만','export-hero',hero()?'':'disabled')}</div>${storageError?'<hr class="divider">'+btn('읽지 못한 원본 내려받기','raw-export')+btn('복구 후 저장 재개','storage-resume','','danger'):''}</div><div class="card"><h2>불러오기</h2><p class="muted">캐릭터 파일은 추가로 가져옵니다. 전체 백업은 기존 기록을 교체하므로 확인 후 적용합니다.</p><label class="field">JSON 파일 선택<input id="import-file" type="file" accept=".json,application/json"></label><p class="small-text">다른 사람의 파일도 내용을 확인한 후 가져오세요. 최대 2MB.</p></div></div><div class="section-head"><h2>최근 기록</h2>${btn('직전 조작 취소','undo',history.length?'':'disabled','quiet')}</div><div class="card">${state.logs.slice(0,60).map(l=>`<div class="log-row"><time>${esc(new Date(l.time).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'}))}</time>${esc(l.text)}</div>`).join('')||'<p class="muted">아직 기록이 없습니다.</p>'}</div><div class="card"><h2>데이터 관리</h2><p class="muted">자동 저장은 이 브라우저에만 남습니다. 브라우저 데이터를 지우면 기록도 사라집니다.</p><div class="actions">${btn('현재 캐릭터 삭제','delete-hero',hero()?'':'disabled','danger quiet')}${btn('전체 초기화','reset-all','','danger quiet')}</div></div>`;}
function askForm(title,fields,submit,callback){modal(title,`<form id="modal-form">${fields}<div class="actions" style="margin-top:20px"><button type="submit" class="primary">${submit}</button>${btn('취소','close')}</div></form>`);$('#modal-form').onsubmit=e=>{e.preventDefault();e.stopPropagation();try{let ok=callback(new FormData(e.currentTarget));if(ok!==false)closeModal();}catch(err){toast(err.message);}};}
function numeric(v,k,min,max){let n=Number(v.get(k));if(!Number.isFinite(n)||n<min||n>max||!Number.isInteger(n))throw Error(`${k} 값을 ${min}~${max} 정수로 입력해주세요.`);return n;}
function useDialog(a){let h=hero();let special=a.name==='만찬과 도살',bag=a.name==='배낭 뒤지기';askForm(a.name,`<p>${esc(a.description||'')}</p><div class="notice">행동력 ${a.ap} · 집중 ${a.focus||0}${a.gold?' · '+a.gold+'G':''}<br>비용과 횟수만 기록합니다. 주사위 판정과 대상 효과는 별도로 반영해주세요.</div>${special?select('mode','만찬과 도살 효과',['도살','연회'],h.mode):''}${bag?select('item','즉시 사용할 물품',[{value:'potion',label:'회복약'},{value:'flash',label:'섬광탄 · 공격 행동'},{value:'smoke',label:'연막탄'}],'potion'):''}<label class="switch-line"><input type="checkbox" name="combat" checked>전투 중 사용 · 행동력과 공격 제한 적용</label><label class="switch-line"><input type="checkbox" name="override">GM 예외 허용 · 제한을 넘어 사용 기록</label>`,'사용 기록',v=>change(()=>{let action={...a};if(special){action.attack=v.get('mode')==='도살';h.mode=v.get('mode');}if(bag)action.attack=v.get('item')==='flash';useAbility(h,action,!!v.get('combat'),!!v.get('override'));},`${h.name}: ${a.name} 사용${v.get('override')?' (GM 예외)':''}. 대상 효과 별도 반영`));}
function healthDialog(h){askForm(h.name+' · 피해와 회복',`${select('kind','처리',['피해','회복'],'피해')}${input('amount','굴린 피해 / 회복 총량',1,'number','min="0" max="999" required')}${input('reduction','피해 감소량',0,'number','min="0" max="999" required')}<p class="inline-note">피해 감소 → 보호막 → 체력 순서. 회복은 오염의 -2를 자동 반영합니다. 드워프·성기사의 감소 사용 횟수는 따로 기록하세요.</p>`,'반영',v=>change(()=>{let amount=numeric(v,'amount',0,999);if(v.get('kind')==='피해')G.damage(h,amount,numeric(v,'reduction',0,999));else G.heal(h,amount,D);},`${h.name}: ${v.get('kind')} ${v.get('amount')} 처리`));}
function startTurn(h){h.ap=h.statuses.some(s=>s.name==='기절')?1:2;h.attacked=false;h.moved=false;delete h.used['turn:mode'];delete h.used['turn:rooted'];}
function finishTurn(h){if(h.statuses.some(s=>s.name==='출혈'))G.damage(h,2);h.statuses=h.statuses.filter(s=>s.name!=='기절');}
function shopDialog(){let h=hero();modal('상점과 장비',`<p><strong>${money(h.gold)}G</strong> · 반입 ${G.slots(h)}/4칸</p>${D.items.map(i=>`<div class="catalog-row"><div><strong>${i.name} · ${i.price}G</strong><p>${i.effect}</p></div>${btn('구매','buy',`data-item="${i.id}"`,'small')}</div>`).join('')}<hr class="divider"><h3>장착 방어구</h3><p>경갑 +1 / 중갑 +2 · 중갑은 은신에 불리</p>${btn(h.armor==='heavy'?'경갑으로 교체 (차액 환급 없음)':'중갑 구매·장착 50G','armor','','quiet')}<hr class="divider"><h3>소지품 정리</h3>${h.inventory.map(i=>`<div class="catalog-row"><span>${D.items.find(x=>x.id===i.item).name}${i.free?' · 지급품':''}</span><div class="actions">${btn('버리기','drop-item',`data-id="${i.id}"`,'small quiet')}${!i.free?btn('판매 5G','sell-item',`data-id="${i.id}"`,'small'):''}</div></div>`).join('')}`);}
function addEnemy(){askForm('적 추가',`${select('type','적 유형',[{value:'rat',label:'기계 생쥐'},{value:'guard',label:'경비병'},{value:'captain',label:'특수부대장'},{value:'boss',label:'결전 병기'}],'guard')}<div class="form-grid">${input('count','추가할 적 수',1,'number','min="1" max="10" required')}${input('players','실제 플레이어 수',state.heroes.length||4,'number','min="3" max="5" required')}${input('die','우선권 D20 눈',10,'number','min="1" max="20" required')}</div><p class="inline-note">같은 종류의 적은 우선권을 함께 굴립니다. 경계 ${state.party.expedition} 단계가 보스에 반영됩니다.</p>`,'추가',v=>change(()=>{if(state.combat.running)throw Error('전투 준비 중에 추가해주세요.');let count=numeric(v,'count',1,10),n=numeric(v,'players',3,5),init=numeric(v,'die',1,20)+2;let stats={rat:['기계 생쥐',8,11,3,3],guard:['경비병',12,12,4,4],captain:['특수부대장',26,13,5,6],boss:['결전 병기',28+12*n+8*(state.party.expedition-1),13,5,6+(state.party.expedition===3?1:0)]}[v.get('type')];for(let i=0;i<count;i++)state.combat.actors.push({id:G.uid(),type:'enemy',name:stats[0]+' '+(i+1),enemyType:v.get('type'),hp:stats[1],max:stats[1],ac:stats[2],bonus:stats[3],damage:stats[4],init});},'적 참가자 추가'));}
async function importFile(file){if(!file)return;if(file.size>2*1024*1024)return toast('파일은 2MB 이하여야 합니다.');try{let obj=JSON.parse(await file.text());if(obj.kind==='manma-character'&&obj.schema===1){let temp=G.empty();temp.heroes=[obj.hero];temp.activeId=obj.hero?.id;G.validateState(temp,D);confirmAction('캐릭터 가져오기',obj.hero.name+' 캐릭터를 새로운 사본으로 추가합니다. 기존 캐릭터는 유지됩니다.',()=>{change(()=>{if(state.heroes.length>=30)throw Error('최대 30명까지 보관할 수 있습니다.');let h=JSON.parse(JSON.stringify(obj.hero));h.id=G.uid();state.heroes.push(h);state.activeId=h.id;},'캐릭터 가져오기');navTo('sheet');});}else{let next=G.validateState(obj,D);confirmAction('전체 기록 교체',`캐릭터 ${next.heroes.length}명과 파티·전투 기록으로 현재 상태를 교체합니다. 현재 기록은 먼저 백업하는 것을 권장합니다.`,()=>{change(()=>{state=next;},'전체 백업 불러오기');navTo('sheet');});}}catch(e){toast('불러오기 실패: '+e.message);}}
const handlers={
close:closeModal,print:()=>window.print(),
'gm-open':()=>{gmOpen=true;render();},'gm-rules':()=>{gmOpen=true;ruleFilter='gm';},
'create-next':()=>{readDraft();try{if(step===1&&!draft.name.trim())throw Error('이름을 입력해주세요.');if(step===2)G.validateDraft(draft,D);step++;render();window.scrollTo(0,0);}catch(e){toast(e.message);}},
'create-prev':()=>{readDraft();step--;render();},'create-reset':()=>confirmAction('생성 입력 초기화','현재 작성 중인 내용만 초기화합니다.',()=>{initDraft();render();}),
'random-race':()=>{readDraft();let roll=()=>{let a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%20+1;},a=roll(),b=roll();modal('종족 D20 두 번',`<div class="grid two">${[a,b].map(n=>{let r=D.races[n-1];return `<div class="card"><div class="result-number">${n}</div><h3>${r.name}</h3><p>${esc(r.trait)}</p>${btn('선택','choose-race',`data-id="${n}"`,'primary')}</div>`;}).join('')}</div><p class="small-text">프로그램으로 굴린 결과입니다. 실물 주사위를 쓰면 선택 목록에서 해당 번호를 고르세요.</p>`);},
'choose-race':b=>{draft.race=+b.dataset.id;closeModal();render();},
'random-job':()=>{readDraft();draft.job=Math.floor(Math.random()*6);render();toast('D6: '+(draft.job+1)+' · '+D.jobs[draft.job].name);},
'random-origin':()=>{readDraft();draft.origin=Math.floor(Math.random()*3);draft.originChoice=D.origins[draft.origin].choice[0]||'';draft.trained=[];render();toast('D3: '+(draft.origin+1)+' · '+D.origins[draft.origin].name);},
'choose-hero':b=>{state.activeId=b.dataset.id;persist();render();},'select-hero':b=>{state.activeId=b.dataset.id;persist();navTo('sheet');},
resource:b=>change(()=>{let h=hero(),k=b.dataset.key;h[k]=G.clamp(h[k]+Number(b.dataset.delta),0,k==='focus'?G.focusMax(h):2);},`${hero().name}: ${b.dataset.key==='focus'?'집중':'행운'} ${b.dataset.delta}`),
health:()=>healthDialog(hero()),
shield:()=>askForm('보호막 수정',`${input('value','현재 보호막',hero().shield,'number','min="0" max="999" required')}<p class="small-text">새 보호막은 기존 값과 합산하지 않고 높은 값을 남깁니다.</p>`,'저장',v=>change(()=>{hero().shield=numeric(v,'value',0,999);},'보호막 수정')),
'edit-resources':()=>{let h=hero();askForm('GM 수동 수정',`<div class="form-grid">${input('hp','현재 체력',h.hp,'number',`min="0" max="${G.maximum(h,D)}" required`)}${input('focus','집중',h.focus,'number',`min="0" max="${G.focusMax(h)}" required`)}${input('luck','행운',h.luck,'number','min="0" max="2" required')}${input('ap','행동력',h.ap,'number','min="0" max="2" required')}${input('gold','개인 골드',h.gold,'number','min="0" max="1000000000" required')}</div><label class="switch-line"><input name="attacked" type="checkbox" ${h.attacked?'checked':''}>이번 턴 공격 사용</label>`,'수정',v=>change(()=>{h.hp=numeric(v,'hp',0,G.maximum(h,D));h.focus=numeric(v,'focus',0,G.focusMax(h));h.luck=numeric(v,'luck',0,2);h.ap=numeric(v,'ap',0,2);h.gold=numeric(v,'gold',0,1e9);h.attacked=!!v.get('attacked');if(h.hp>0){h.crisis=0;h.stable=false;}},h.name+': GM 수동 수정'));},
'status-add':()=>askForm('상태 추가',`${select('name','상태',['방해','속박','출혈','오염','기절'],'방해')}${input('source','부여자','','text','maxlength="100"')}${input('until','종료 시점','','text','maxlength="200" placeholder="예: 미루의 다음 턴 종료"')}`,'추가',v=>change(()=>{let h=hero(),name=v.get('name');h.statuses=h.statuses.filter(s=>s.name!==name);h.statuses.push({name,source:String(v.get('source')),until:String(v.get('until'))});},hero().name+': '+v.get('name')+' 추가')),
'status-remove':b=>change(()=>{hero().statuses.splice(+b.dataset.i,1);},hero().name+': 상태 해제'),
crisis:()=>askForm('위기 판정',`${input('die','D6 눈','','number','min="1" max="6" required')}<p class="small-text">1~2는 위기 +1, 3~6은 변화 없음. 위기 3이면 중상입니다.</p>`,'반영',v=>change(()=>{let h=hero();if(h.hp>0||h.stable||h.injured)throw Error('현재 위기 판정 대상이 아닙니다.');if(numeric(v,'die',1,6)<=2)h.crisis++;if(h.crisis>=3){h.crisis=3;h.injured=true;}},hero().name+': 위기 판정')),
stabilize:()=>change(()=>{let h=hero();if(h.hp>0||h.injured)throw Error('안정화 대상이 아닙니다.');h.stable=true;},hero().name+': 응급 처치 성공 후 안정화 기록'),
skill:b=>useDialog(job(hero()).skills.find(s=>s.id===b.dataset.id)),
'skill-roll':b=>{rollPreset='직업 · '+job(hero()).skills.find(s=>s.id===b.dataset.id).name;lastRoll=null;navTo('roll');},
basic:()=>{let h=hero();let magic=h.job===1?'마도 화살':h.job===2?'신성탄':'';useDialog({id:'basic',name:'기본 공격',description:`${h.weapon}: D20 + ${h.weapon==='총기'?'민첩':'근력'} + 해당 숙련. 피해 D6 + 능력치.${magic?' '+magic+'도 선택 가능하며 직업 설명의 명중·피해를 사용합니다.':''}`,ap:1,focus:0,attack:true});},
defend:()=>useDialog({id:'defend',name:'방어',description:'다음 자기 턴 시작까지 방어도 +2. 방어도 표시는 기본값이므로 판정할 때 보정해주세요. 중첩하지 않습니다.',ap:1,focus:0}),
move:()=>change(()=>{let h=hero();if(h.statuses.some(s=>s.name==='속박'))throw Error('속박을 먼저 해제해주세요.');if(h.used['turn:rooted'])throw Error('뿌리내리기를 사용한 턴에는 이동할 수 없습니다.');useAbility(h,{id:'move',ap:1});h.moved=true;},hero().name+': 한 구역 이동'),
assist:()=>useDialog({id:'assist',name:'도움',description:'다음 자기 턴 시작 전 동료 한 명의 다음 판정에 상황 +2. 대상에게 알려주세요.',ap:1,focus:0}),
mode:()=>change(()=>{let h=hero();if(h.used['turn:mode'])throw Error('모드 전환은 턴당 한 번입니다.');useAbility(h,{id:'mode',ap:1});h.used['turn:mode']=true;if(!h.used['battle:modeheal']){h.used['battle:modeheal']=true;toast('이번 전투 첫 전환입니다. 선택한 대상에게 체력 2 회복을 반영하세요.');}h.mode=h.mode==='도살'?'연회':'도살';},hero().name+': 모드 전환. 전투당 첫 전환의 체력 2 회복은 대상 시트에서 반영'),
turn:()=>confirmAction('내 턴 시작','GM이 내 차례라고 안내했을 때만 사용하세요. 행동력과 공격 사용 여부를 초기화합니다. 상태 종료와 지난 턴 출혈은 별도로 처리하세요.',()=>change(()=>startTurn(hero()),hero().name+': 턴 시작')),
'battle-reset':()=>confirmAction('새 전투 시작','새로운 전투임을 GM에게 확인하세요. 내 전투당 사용 횟수와 보호막을 초기화합니다.',()=>change(()=>{let h=hero();G.markReset(h,'battle');h.shield=0;startTurn(h);},hero().name+': 새 전투 초기화')),
race:()=>{let h=hero(),r=race(h);if(r.period==='passive')return;askForm(r.name+' · 종족 특성',`<p>${esc(r.trait)}</p><p class="notice">자신의 회복·속박 해제·악마 체력 비용은 자동 반영합니다. 피해 감소, 다른 대상의 보호막·밀치기 등은 별도 반영하세요.</p>${r.id===8?'<p>체력 3을 실제로 지불합니다. 보호막은 사용하지 않습니다.</p>':''}<label class="switch-line"><input name="combat" type="checkbox" checked>전투 중 · 행동력 적용</label><label class="switch-line"><input name="override" type="checkbox">GM 예외 허용</label>`,'사용 기록',v=>change(()=>{if(!v.get('combat')&&r.period==='battle')throw Error('전투당 특성은 실제 전투 중에만 사용할 수 있습니다.');if(r.id===8&&h.hp<4)throw Error('체력이 최소 4 필요합니다.');if(r.id===13&&!h.attacked)throw Error('인접 공격에 명중한 직후 사용하세요. 먼저 공격을 기록해주세요.');if(r.id===18&&h.moved)throw Error('이미 이동한 턴에는 뿌리내릴 수 없습니다.');useAbility(h,{id:'race',ap:r.ap,focus:0,period:r.period,attack:r.attack},!!v.get('combat'),!!v.get('override'));if(r.id===8)h.hp-=3;if(r.id===10||r.id===15)h.statuses=h.statuses.filter(s=>s.name!=='속박');if(r.id===10)h.moved=true;if(r.id===13)G.heal(h,3,D);if(r.id===15)G.heal(h,2,D);if(r.id===18){G.heal(h,4,D);h.used['turn:rooted']=true;}},h.name+': '+r.name+' 특성 기록'));},
'short-rest':()=>askForm('짧은 휴식',`${input('die','체력 회복 D6 눈','','number','min="1" max="6" required')}<p>체력 D6+근력, 집중 1 회복. 진입당 한 번.<br>인공체의 추가 회복과 오염은 자동 반영됩니다.</p>`,'휴식',v=>change(()=>G.shortRest(hero(),numeric(v,'die',1,6),D),hero().name+': 짧은 휴식')),
'long-rest':()=>confirmAction('긴 휴식','피난처에서 6시간 쉴 수 있다고 GM이 허용했나요? 체력·집중·상태 이상을 회복합니다. 모임당·진입당 횟수는 유지합니다.',()=>change(()=>G.longRest(hero(),D),hero().name+': 긴 휴식')),
level:()=>askForm('레벨 업',`<p>AI 구출 시 레벨 2, 봉쇄 해제 키 획득 시 레벨 3입니다. 해당 이정표를 달성했는지 확인하세요.</p>${select('skill','추가 숙련 하나',D.skills.filter(s=>!hero().trained.includes(s.name)).map(s=>s.name),'')}`,'레벨 업',v=>change(()=>G.levelUp(hero(),v.get('skill'),D),hero().name+': 레벨 업')),
'edit-story':()=>{let h=hero();askForm('캐릭터 설정 수정',`${input('name','이름',h.name,'text','maxlength="60" required')}${input('gender','성별·호칭',h.gender,'text','maxlength="80"')}${input('appearance','외형·나이',h.appearance,'text','maxlength="500"')}${input('goal','목표',h.goal,'text','maxlength="500"')}${input('bond','관계',h.bond,'text','maxlength="500"')}${input('oath','서약',h.oath,'text','maxlength="300"')}`,'저장',v=>change(()=>{for(let k of ['name','gender','appearance','goal','bond','oath'])h[k]=String(v.get(k)).trim();if(!h.name)throw Error('이름을 입력해주세요.');state.combat.actors.filter(a=>a.heroId===h.id).forEach(a=>a.name=h.name);},h.name+': 설정 수정'));},
shop:shopDialog,
buy:b=>{if(change(()=>{let h=hero(),i=D.items.find(x=>x.id===b.dataset.item);if(G.slots(h)>=4)throw Error('반입 칸이 가득 찼습니다.');if(h.gold<i.price)throw Error('골드가 부족합니다.');h.gold-=i.price;h.inventory.push({id:G.uid(),item:i.id,free:false,slots:1});},hero().name+': 물품 구매'))shopDialog();},
armor:()=>{let h=hero();confirmAction('방어구 교체',h.armor==='heavy'?'경갑으로 교체합니다. 구매 비용은 돌려받지 않습니다.':'50G를 지불하고 중갑으로 교체합니다. 은신 판정에 불리가 적용됩니다.',()=>{change(()=>{if(h.armor==='light'){if(h.gold<50)throw Error('골드가 부족합니다.');h.gold-=50;h.armor='heavy';}else h.armor='light';},h.name+': 방어구 교체');});},
'drop-item':b=>{if(change(()=>hero().inventory=hero().inventory.filter(i=>i.id!==b.dataset.id),hero().name+': 물품 버림'))shopDialog();},
'sell-item':b=>{if(change(()=>{let h=hero(),i=h.inventory.find(i=>i.id===b.dataset.id);if(i.free)throw Error('지급품은 판매할 수 없습니다.');h.gold+=D.items.find(x=>x.id===i.item).price/2;h.inventory=h.inventory.filter(x=>x.id!==i.id);},hero().name+': 물품 판매'))shopDialog();},
item:b=>{let h=hero(),i=h.inventory.find(x=>x.id===b.dataset.id),item=D.items.find(x=>x.id===i.item);askForm(item.name+' 사용',`<p>${esc(item.effect)}</p><p class="small-text">아이템과 행동력만 소비합니다. 회복·상태 효과는 대상 시트에서 반영해주세요.</p><label class="switch-line"><input name="combat" type="checkbox" checked>전투 중 사용</label>`,'사용·소비',v=>change(()=>{useAbility(h,{id:'item',ap:i.item==='tool'?0:1,attack:i.item==='flash'},!!v.get('combat'));h.inventory=h.inventory.filter(x=>x.id!==i.id);},h.name+': '+item.name+' 소비. 대상 효과 별도 반영'));},
reroll:()=>{let h=hero();if(!lastRoll||lastRoll.retried||lastRoll.heroId!==h.id)return;confirmAction('행운 사용','행운 1을 지불합니다. 같은 조건으로 주사위를 다시 굴려 입력하세요.',()=>{if(change(()=>{if(h.luck<1)throw Error('행운이 부족합니다.');h.luck--;},h.name+': 재굴림 행운 1 소비')){lastRoll.retried=true;lastRoll.pending=true;render();toast('같은 판정 조건으로 새 눈을 입력해주세요.');}});},
'party-money':b=>askForm('공용 골드 입출금',`${select('direction','처리',['입금','출금'],'입금')}${input('amount','금액',10,'number','min="1" max="1000000000" required')}<p class="small-text">개인 시트의 골드는 자동으로 이동하지 않습니다. 개인 골드도 함께 수정하세요.</p>`,'반영',v=>change(()=>{let n=numeric(v,'amount',1,1e9);if(v.get('direction')==='출금'&&state.party.gold<n)throw Error('공용 골드가 부족합니다.');state.party.gold+=v.get('direction')==='입금'?n:-n;},'공용 골드 '+v.get('direction'))),
debt:()=>askForm('차입과 상환',`${select('kind','처리',['차입','상환'],'차입')}${input('amount','금액',10,'number','min="1" max="1000000" required')}<p class="small-text">차입 시 공용 골드가 늘고, 상환 시 공용 골드에서 지불합니다. 일반 차입 잔액은 최대 50G입니다.</p>`,'반영',v=>change(()=>{let p=state.party,n=numeric(v,'amount',1,1e6);if(v.get('kind')==='차입'){if(p.debt+n>50)throw Error('일반 차입 잔액 한도는 50G입니다.');p.debt+=n;p.gold+=n;}else{if(p.gold<n||p.debt<n)throw Error('상환액이 골드 또는 부채보다 큽니다.');p.gold-=n;p.debt-=n;}},'부채 '+v.get('kind'))),
trust:b=>change(()=>{state.party.trust=G.clamp(state.party.trust+Number(b.dataset.delta),-2,2);},'AI 신뢰 변경'),
'next-expedition':()=>confirmAction('다음 진입','모든 기록된 캐릭터의 진입당 횟수를 초기화합니다. 체력·집중은 긴 휴식을 별도로 진행해야 회복됩니다. 이전 층 상자는 다시 생성되지 않습니다.',()=>change(()=>G.newExpedition(state),'새 탐색 진입')),
chest:()=>askForm('층별 상자',`${select('floor','층',[{value:0,label:'지하층'},{value:1,label:'1층'},{value:2,label:'2층'},{value:3,label:'3층'},{value:4,label:'4층'}].filter(x=>!state.party.chests.includes(x.value)),'')}${input('die','보상 D6 눈','','number','min="1" max="6" required')}<p class="small-text">1~2: 20G / 3~4: 40G / 5: 60G / 6: 100G. GM이 상자를 열었다고 확인한 뒤 기록하세요.</p>`,'획득',v=>change(()=>{if(!v.has('floor')||v.get('floor')===null)throw Error('모든 층 상자를 열었습니다.');let floor=Number(v.get('floor'));if(state.party.chests.includes(floor))throw Error('이미 개봉한 상자입니다.');if(state.party.loot.length>=6)throw Error('배낭이 가득 찼습니다.');let die=numeric(v,'die',1,6),value=die<3?20:die<5?40:die===5?60:100;state.party.loot.push({name:(floor===0?'지하층':floor+'층')+' 전리품',value});state.party.chests.push(floor);},'상자 개봉과 전리품 획득')),
'loot-add':()=>askForm('전리품 직접 추가',`${input('name','이름','','text','maxlength="100" required')}${input('value','매각가',20,'number','min="0" max="1000000" required')}`,'추가',v=>change(()=>{if(state.party.loot.length>=6)throw Error('배낭이 가득 찼습니다.');state.party.loot.push({name:String(v.get('name')),value:numeric(v,'value',0,1e6)});},'전리품 추가')),
'sell-loot':b=>change(()=>{let p=state.party,x=p.loot[+b.dataset.i];p.gold+=x.value;p.loot.splice(+b.dataset.i,1);},'전리품 매각 · 공용 골드 입금'),
'discard-loot':b=>confirmAction('전리품 버리기','보상을 받지 않고 배낭에서 제거합니다.',()=>change(()=>state.party.loot.splice(+b.dataset.i,1),'전리품 버림')),
'actor-pc':()=>{let arr=state.heroes.filter(h=>!state.combat.actors.some(a=>a.heroId===h.id));if(!arr.length)return toast('추가할 캐릭터가 없습니다. 먼저 만들거나 파일을 가져오세요.');askForm('플레이어 추가',`${select('hero','캐릭터',arr.map(h=>({value:h.id,label:h.name})),arr[0].id)}${input('die','우선권 D20 눈',10,'number','min="1" max="20" required')}`,'추가',v=>change(()=>{let h=state.heroes.find(x=>x.id===v.get('hero'));state.combat.actors.push({id:G.uid(),type:'pc',heroId:h.id,name:h.name,hp:h.hp,max:G.maximum(h,D),ac:G.defense(h),bonus:0,damage:0,init:numeric(v,'die',1,20)+h.stats['민첩']});},'플레이어 전투 참가'));},
'actor-enemy':addEnemy,
'actor-hp':b=>{let a=state.combat.actors.find(x=>x.id===b.dataset.id);if(a.type==='pc')return healthDialog(state.heroes.find(h=>h.id===a.heroId));askForm(a.name+' 체력',input('hp','남은 체력',a.hp,'number',`min="0" max="${a.max}" required`),'저장',v=>change(()=>a.hp=numeric(v,'hp',0,a.max),a.name+': 체력 수정'));},
'actor-init':b=>{let a=state.combat.actors.find(x=>x.id===b.dataset.id);askForm('우선권 수정',input('init','보정 포함 합계',a.init,'number','min="0" max="99" required'),'저장',v=>change(()=>a.init=numeric(v,'init',0,99),'우선권 수정'));},
'actor-remove':b=>change(()=>{if(state.combat.running)throw Error('전투 중에는 제외할 수 없습니다. 체력을 0으로 표시하세요.');state.combat.actors=state.combat.actors.filter(a=>a.id!==b.dataset.id);},'참가자 제외'),
'combat-start':()=>change(()=>{let c=state.combat;if(!c.actors.length)throw Error('참가자를 추가해주세요.');c.actors.sort((a,b)=>b.init-a.init||(a.type===b.type?0:a.type==='pc'?-1:1));c.running=true;c.index=0;c.round=1;c.pattern=0;for(let a of c.actors)if(a.type==='pc'){let h=state.heroes.find(h=>h.id===a.heroId);G.markReset(h,'battle');h.shield=0;}let a=c.actors[0];if(a.type==='pc')startTurn(state.heroes.find(h=>h.id===a.heroId));},'전투 시작'),
'combat-next':()=>change(()=>{let c=state.combat;if(!c.running||!c.actors.length)throw Error('진행 중인 전투가 없습니다.');let a=c.actors[c.index];if(a.type==='pc')finishTurn(state.heroes.find(h=>h.id===a.heroId));let checked=0;do{c.index++;if(c.index>=c.actors.length){c.index=0;c.round++;}a=c.actors[c.index];checked++;}while(a.type==='enemy'&&a.hp===0&&checked<=c.actors.length);if(a.type==='pc')startTurn(state.heroes.find(h=>h.id===a.heroId));},'다음 턴 · 이전 플레이어 출혈 처리'),
'combat-end':()=>confirmAction('전투 종료','플레이어의 보호막과 출혈을 제거합니다. 다른 상태는 종료 조건에 맞게 직접 해제하세요.',()=>change(()=>{state.combat.running=false;state.heroes.forEach(h=>{h.shield=0;h.statuses=h.statuses.filter(s=>s.name!=='출혈');});},'전투 종료')),
'combat-clear':()=>confirmAction('새 전투 준비','현재 전투 참가자 목록과 순서를 비웁니다. 캐릭터는 삭제하지 않습니다.',()=>change(()=>state.combat={running:false,round:1,index:0,actors:[],pattern:0},'전투 목록 초기화')),
pattern:()=>{let p=state.combat.pattern;modal('보스 공개 패턴',`<span class="pill">예고 ${p+1}</span><h2>${p%2===0?'충전 광선':'전자기 폭풍'}</h2><p>${p%2===0?'한 구역을 지정합니다. 다음 턴 그 구역의 아군 최대 2명에게 명중 +5, 피해 8. 구역 밖으로 이동하면 피합니다.':'중앙 구역 밖의 아군 최대 2명에게 명중 +5, 피해 5와 다음 병기 턴 시작까지 방해. 중앙 이동 또는 봉인으로 대응합니다.'}</p><p class="small-text">첫 턴은 기본 공격입니다. 이후 턴 종료에 예고하세요. 패턴 진행은 수동이며 자동 공격하지 않습니다.</p>${btn('이 예고 기록·다음 패턴으로','pattern-next','','primary')}`);},
'pattern-next':()=>{change(()=>state.combat.pattern++,'보스 패턴 예고 기록');closeModal();},
'scene-reset':()=>change(()=>state.heroes.forEach(h=>G.markReset(h,'scene')),'새 탐색 장면 · 장면당 특성 초기화'),
'session-reset':()=>confirmAction('새 모임 시작','실제 새 모임일 때 사용하세요. 모든 캐릭터의 행운을 2로, 모임당 사용 횟수를 미사용으로 초기화합니다.',()=>change(()=>{if(state.party.marathon)throw Error('정주행 중에는 모임당 횟수와 행운을 초기화할 수 없습니다.');state.heroes.forEach(h=>{G.markReset(h,'session');h.luck=2;});},'새 모임 시작')),
'marathon-enable':()=>confirmAction('정주행 규칙 적용','이번 모험 전체에 각 모임당 능력을 총 3회 사용할 수 있습니다. 이미 쓴 횟수는 유지하고 행운은 회복하지 않습니다. 모험 시작 전에 적용해주세요.',()=>change(()=>{if(state.party.oneshotUsed)throw Error('기존 완주형 회복을 이미 사용했습니다. 새 모험에서 정주행 규칙을 적용해주세요.');state.party.marathon=true;},'정주행 적용: 모임당 능력 각각 총 3회')),
'export-all':()=>download('만마_TRPG_전체백업_'+new Date().toISOString().slice(0,10)+'.json',state),
'export-hero':()=>{let h=hero();if(h)download(h.name.replace(/[^\w가-힣-]/g,'_')+'_캐릭터.json',{kind:'manma-character',schema:1,ruleVersion:'1.1',hero:h});else toast('먼저 캐릭터를 선택해주세요.');},
'raw-export':()=>{try{download('만마_저장원본.txt',localStorage.getItem(KEY)||'기록 없음','text/plain');}catch(e){toast('원본에 접근할 수 없습니다.');}},
'storage-resume':()=>confirmAction('저장 재개','현재 화면의 상태로 저장 파일을 덮어씁니다. 원본이 필요하면 먼저 다운로드해주세요.',()=>{storageError='';persist();render();}),
undo:()=>{if(!history.length)return toast('취소할 조작이 없습니다.');state=JSON.parse(history.pop());lastRoll=null;persist();render();toast('직전 조작을 취소했습니다.');},
'delete-hero':()=>confirmAction('캐릭터 삭제',hero().name+'의 시트와 전투 참가 기록을 삭제합니다.',()=>change(()=>{let id=state.activeId;state.heroes=state.heroes.filter(h=>h.id!==id);state.activeId=state.heroes[0]?.id||null;state.combat.actors=state.combat.actors.filter(a=>a.heroId!==id);state.combat.index=0;state.combat.running=false;},'캐릭터 삭제')),
'reset-all':()=>confirmAction('전체 초기화','모든 캐릭터·파티·전투 기록을 지웁니다. 먼저 백업을 다운로드하세요.',()=>change(()=>state=G.empty(),'전체 초기화'))
};
document.addEventListener('click',e=>{let b=e.target.closest('[data-action]');if(!b||b.disabled)return;let fn=handlers[b.dataset.action];if(fn){if(b.tagName==='A'&&b.dataset.action!=='gm-rules')e.preventDefault();try{fn(b);}catch(err){toast(err.message);}}});
document.addEventListener('change',e=>{let x=e.target;if(x.id==='hero-pick'){state.activeId=x.value;lastRoll=null;persist();render();}if(x.id==='rule-filter'){if(x.value==='gm'&&!gmOpen){x.value='player';confirmAction('GM 규칙 열기','숨겨진 진실과 결말이 포함되어 있습니다. 계속할까요?',()=>{gmOpen=true;ruleFilter='gm';render();});}else{ruleFilter=x.value;drawRules();}}if(x.dataset.clue){change(()=>{let c=x.dataset.clue;state.party.clues=x.checked?[...new Set([...state.party.clues,c])]:state.party.clues.filter(y=>y!==c);},'파티 단서 변경');}if(x.id==='import-file')importFile(x.files[0]);});
document.addEventListener('input',e=>{if(e.target.id==='rule-search'){search=e.target.value;drawRules();}});
document.addEventListener('submit',e=>{if(e.target.id==='creator'){e.preventDefault();readDraft();if(change(()=>{if(state.heroes.length>=30)throw Error('최대 30명까지 보관할 수 있습니다.');let h=G.createHero(draft,D);state.heroes.push(h);state.activeId=h.id;},draft.name+': 캐릭터 생성')){draft=null;navTo('sheet');}}if(e.target.id==='notes-form'){e.preventDefault();let v=new FormData(e.target);change(()=>state.party.notes=String(v.get('notes')),'파티 메모 저장');}if(e.target.id==='roll-form'){e.preventDefault();let f=e.target,v=new FormData(f),h=hero();try{let params={die:Number(v.get('die')),die2:Number(v.get('die2')),mode:v.get('mode'),stat:h.stats[v.get('stat')],trained:!!v.get('trained'),modifier:numeric(v,'modifier',-2,2),dc:numeric(v,'dc',1,99),attack:!!v.get('attack')};let retried=!!lastRoll?.pending;if(retried){if(v.get('skill')!==lastRoll.skill)throw Error('이전과 같은 행동을 선택해주세요.');let old=lastRoll.params;for(let k of ['mode','stat','trained','modifier','dc','attack'])if(params[k]!==old[k])throw Error('재굴림은 이전과 같은 판정 조건을 사용해야 합니다.');}let result=G.rollResult(params);lastRoll={heroId:h.id,skill:v.get('skill'),statName:v.get('stat'),params,result,retried,pending:false};change(()=>{},`${h.name}: ${v.get('skill')} ${result.total} · ${result.success?'성공':'실패'}${retried?' (재굴림)':''}`);showRoll();}catch(err){toast(err.message);}}});
$('#modal-close').onclick=closeModal;$('#backup-top').onclick=handlers['export-all'];window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});window.addEventListener('storage',e=>{if(e.key===KEY&&!window.Cloud?.active){storageError='다른 탭에서 기록이 바뀌어 자동 저장을 멈췄습니다. 새로고침하거나 백업 후 저장을 재개해주세요.';render();toast('다른 탭의 변경을 감지했습니다. 새로고침해주세요.');}});
render();
