(function(root){
'use strict';
const C=root.SyncCore;
const cloud={active:false,ready:false,pending:false,uid:null,code:null,gm:false,meta:null,records:{},members:[],events:[],unsubs:[],history:[],onUpdate:()=>{},onStatus:()=>{},onError:()=>{}};
let db,auth,F,A,loading;
cloud.configured=()=>['apiKey','authDomain','projectId','appId'].every(k=>typeof root.FIREBASE_CONFIG?.[k]==='string'&&root.FIREBASE_CONFIG[k].trim());
cloud.init=async()=>{if(auth?.currentUser){cloud.uid=auth.currentUser.uid;return auth.currentUser;}if(loading)return loading;if(!cloud.configured())throw Error('firebase-config.js에 Firebase 웹 앱 설정을 먼저 입력해주세요.');loading=(async()=>{const [B,a,f]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js')]);A=a;F=f;const fresh=!B.getApps().length;const app=fresh?B.initializeApp(root.FIREBASE_CONFIG):B.getApp();auth=A.getAuth(app);db=F.getFirestore(app);if(fresh&&root.MANMA_EMULATORS===true){A.connectAuthEmulator(auth,'http://127.0.0.1:9099',{disableWarnings:true});F.connectFirestoreEmulator(db,'127.0.0.1',8080);}await A.setPersistence(auth,A.browserLocalPersistence);await auth.authStateReady();if(!auth.currentUser)await A.signInAnonymously(auth);cloud.uid=auth.currentUser.uid;return auth.currentUser;})();try{return await loading;}finally{loading=null;}};
const roomRef=code=>F.doc(db,'rooms',code),recordRef=id=>F.doc(db,'rooms',cloud.code,'state',id);
const newRecord=(kind,ownerUid,payload,rev=1)=>({kind,ownerUid,payload:C.clone(payload),rev,token:crypto.randomUUID()});
function remember(){try{localStorage.setItem('manma-last-room',JSON.stringify({code:cloud.code,uid:cloud.uid}));}catch{}}
function emit(){cloud.onUpdate({records:C.clone(cloud.records),events:C.clone(cloud.events)});cloud.onStatus();}
function receive(snap){if(snap.metadata.hasPendingWrites)return;cloud.ready=!snap.metadata.fromCache&&navigator.onLine;cloud.onStatus();if(snap.metadata.fromCache)return;let rec={};snap.forEach(d=>rec[d.id]=d.data());cloud.records=rec;emit();}
function subscribe(code,meta){cloud.unsubs.forEach(f=>f());cloud.unsubs=[];cloud.active=true;cloud.code=code;cloud.meta=meta;cloud.gm=meta.gmUid===cloud.uid;cloud.ready=false;cloud.records={};cloud.history=[];remember();
 const failed=e=>{cloud.ready=false;cloud.onStatus();cloud.onError('공유 연결 실패: '+friendly(e));};
 cloud.unsubs.push(F.onSnapshot(F.collection(db,'rooms',code,'state'),{includeMetadataChanges:true},receive,failed));
 cloud.unsubs.push(F.onSnapshot(roomRef(code),s=>{if(s.exists()){cloud.meta=s.data();cloud.onStatus();}},failed));
 cloud.unsubs.push(F.onSnapshot(F.collection(db,'rooms',code,'members'),s=>{cloud.members=s.docs.map(d=>({uid:d.id,...d.data()}));cloud.onStatus();},failed));
 cloud.unsubs.push(F.onSnapshot(F.query(F.collection(db,'rooms',code,'events'),F.orderBy('createdAt','desc'),F.limit(100)),s=>{if(s.metadata.hasPendingWrites)return;cloud.events=s.docs.map(d=>{let v=d.data();return {text:v.text,time:v.createdAt?.toDate?.().toISOString()||new Date().toISOString(),authorUid:v.authorUid};});emit();},failed));
}
cloud.create=async(name,local)=>{await cloud.init();if(!navigator.onLine)throw Error('인터넷 연결이 필요합니다.');const code=C.code(),meta={gmUid:cloud.uid,title:name.slice(0,60)||'TRPG의 밤',open:true,version:2,createdAt:F.serverTimestamp()};let seed=C.clone(local);await F.runTransaction(db,async tx=>{const r=roomRef(code),old=await tx.get(r);if(old.exists())throw Error('초대 코드가 겹쳤습니다. 다시 생성해주세요.');tx.set(r,meta);tx.set(F.doc(db,'rooms',code,'members',cloud.uid),{name:'GM',joinedAt:F.serverTimestamp()});tx.set(F.doc(db,'rooms',code,'state','board'),newRecord('board',cloud.uid,C.board(seed)));for(let h of seed.heroes)tx.set(F.doc(db,'rooms',code,'state',h.id),newRecord('hero',cloud.uid,h));});subscribe(code,{...meta,createdAt:null});return code;};
cloud.join=async(rawCode,name)=>{await cloud.init();const code=C.cleanCode(rawCode);const snap=await F.getDocFromServer(roomRef(code));if(!snap.exists())throw Error('존재하지 않는 방입니다. 코드를 확인해주세요.');const meta=snap.data();if(meta.version!==2)throw Error('지원하지 않는 공유 방 버전입니다.');let member=F.doc(db,'rooms',code,'members',cloud.uid);await F.runTransaction(db,async tx=>{const old=await tx.get(member);if(!old.exists()){if(!meta.open&&meta.gmUid!==cloud.uid)throw Error('GM이 새 참가자 입장을 잠갔습니다.');tx.set(member,{name:String(name||'플레이어').slice(0,40),joinedAt:F.serverTimestamp()});}});subscribe(code,meta);};
cloud.refresh=async()=>{if(!cloud.active)return;try{receive(await F.getDocsFromServer(F.collection(db,'rooms',cloud.code,'state')));}catch(e){cloud.ready=false;cloud.onStatus();throw e;}};
async function write(patches,text){if(!cloud.ready||!navigator.onLine)throw Error('서버 연결을 확인한 뒤 다시 시도해주세요. 연결이 끊긴 동안 변경은 저장하지 않습니다.');const tokens={};const event=F.doc(F.collection(db,'rooms',cloud.code,'events'));
 await F.runTransaction(db,async tx=>{let current={};for(let p of patches){const snap=await tx.get(recordRef(p.id));current[p.id]=snap.exists()?snap.data():null;}C.checkVersions(patches,current);for(let p of patches){if(p.after===null){tx.delete(recordRef(p.id));tokens[p.id]=null;}else{let r=newRecord(p.kind,p.ownerUid,p.after,(current[p.id]?.rev||0)+1);tokens[p.id]=r.token;tx.set(recordRef(p.id),r);}}tx.set(event,{authorUid:cloud.uid,text:String(text).slice(0,500),createdAt:F.serverTimestamp()});});return tokens;}
cloud.commit=async(before,after,records,text)=>{if(cloud.pending)throw Error('이전 변경을 저장 중입니다.');let patches=C.plan(before,after,records,cloud.uid,cloud.gm);cloud.pending=true;cloud.onStatus();try{let tokens=await write(patches,text);if(patches.length){cloud.history.push({patches,tokens});if(cloud.history.length>20)cloud.history.shift();}return true;}finally{cloud.pending=false;cloud.onStatus();}};
cloud.undo=async()=>{let h=cloud.history.at(-1);if(!h)throw Error('이 기기에서 취소할 공유 변경이 없습니다.');if(cloud.pending)throw Error('저장 완료를 기다려주세요.');cloud.pending=true;cloud.onStatus();try{await write(C.reverse(h.patches,h.tokens),'내 직전 변경 취소');cloud.history.pop();}finally{cloud.pending=false;cloud.onStatus();}};
cloud.lock=async()=>{if(!cloud.gm)throw Error('GM만 입장을 잠글 수 있습니다.');await F.runTransaction(db,async tx=>{const r=roomRef(cloud.code),s=await tx.get(r);tx.update(r,{open:!s.data().open});});};
cloud.leave=()=>{cloud.unsubs.forEach(f=>f());cloud.unsubs=[];cloud.active=false;cloud.ready=false;cloud.code=null;cloud.records={};cloud.events=[];cloud.members=[];cloud.history=[];try{localStorage.removeItem('manma-last-room');}catch{}cloud.onStatus();};
cloud.resumeInfo=()=>{try{return JSON.parse(localStorage.getItem('manma-last-room')||'null');}catch{return null;}};
function friendly(e){return ({'permission-denied':'접근 권한이 없습니다. 보안 규칙과 방 참가 상태를 확인하세요.','auth/operation-not-allowed':'Firebase Authentication에서 익명 로그인을 켜주세요.','auth/unauthorized-domain':'Firebase에 GitHub Pages 도메인을 등록해주세요.','unavailable':'서버에 연결할 수 없습니다. 잠시 후 재연결해주세요.'})[e.code]||e.message||String(e);}
cloud.friendly=friendly;
window.addEventListener('offline',()=>{cloud.ready=false;cloud.onStatus();});window.addEventListener('online',()=>{if(cloud.active)cloud.refresh().catch(e=>cloud.onError(friendly(e)));});root.Cloud=cloud;
})(globalThis);
