(function(root){
'use strict';
const STATS=['근력','민첩','지능','감각','의지'];
const clamp=(v,min,max)=>Math.min(max,Math.max(min,Number(v)||0));
const uid=()=>globalThis.crypto?.randomUUID?.() || 'id-'+Date.now()+'-'+Math.random().toString(36).slice(2);
function empty(){return {schema:1,ruleVersion:'1.1',heroes:[],activeId:null,party:{gold:0,debt:0,expedition:1,trust:0,loot:[],chests:[],clues:[],notes:''},combat:{running:false,round:1,index:0,actors:[],pattern:0},logs:[]};}
function maximum(h,data){return data.jobs[h.job].hp+h.stats['근력']*2+(h.level-1)*3;}
function defense(h){return 10+h.stats['민첩']+(h.armor==='heavy'?2:1);}
function focusMax(h){return h.level>=2?4:3;}
function validateDraft(d,data){if(!d.name.trim())throw Error('캐릭터 이름을 입력해주세요.');if(!data.races.find(r=>r.id===d.race)||!data.jobs[d.job]||!data.origins[d.origin])throw Error('종족·직업·출신을 확인해주세요.');if(STATS.map(k=>Number(d.stats[k])).sort().join(',')!=='0,1,1,2,3')throw Error('능력치 3, 2, 1, 1, 0을 하나씩 배치해주세요.');let origin=data.origins[d.origin];if(origin.choice.length&&!origin.choice.includes(d.originChoice))throw Error('출신 숙련을 선택해주세요.');let extra=origin.skills.concat(origin.choice.length?[d.originChoice]:[]);if(d.trained.length!==4||new Set([...d.trained,...extra]).size!==4+extra.length)throw Error('출신 숙련과 겹치지 않는 공통 숙련 4개를 선택해주세요.');if(!d.trained.every(n=>data.skills.some(x=>x.name===n)))throw Error('알 수 없는 숙련입니다.');}
function createHero(d,data){validateDraft(d,data);let o=data.origins[d.origin];let h={id:uid(),name:d.name.trim().slice(0,60),gender:d.gender.slice(0,80),appearance:d.appearance.slice(0,500),goal:d.goal.slice(0,500),bond:d.bond.slice(0,500),oath:d.oath.slice(0,300),race:Number(d.race),job:Number(d.job),origin:Number(d.origin),originChoice:d.originChoice,level:1,stats:{...d.stats},trained:[...d.trained,...o.skills,...(o.choice.length?[d.originChoice]:[])],armor:'light',weapon:d.weapon||'총기',gold:30+o.gold,focus:3,luck:2,shield:0,hp:0,ap:2,attacked:false,moved:false,mode:'도살',crisis:0,stable:false,injured:false,statuses:[],used:{},inventory:[{id:uid(),item:'potion',free:true,slots:1},{id:uid(),item:'tool',free:true,slots:1}]};if(h.race===5)h.inventory.push({id:uid(),item:'tool',free:true,slots:0});if(h.job===4)h.inventory.push({id:uid(),item:'flash',free:true,temporary:true,slots:1});h.hp=maximum(h,data);return h;}
function slots(h){return h.inventory.reduce((a,x)=>a+x.slots,0);}
function markReset(h,period){Object.keys(h.used).filter(k=>k.startsWith(period+':')).forEach(k=>delete h.used[k]);}
function usageCount(h,a){return Number(h.used[a.period+':'+a.id]||0);}
function usageLimit(a,sessionLimit=1){return a.period==='session'&&sessionLimit===3?3:1;}
function canUse(h,a,combat=true,sessionLimit=1){if(h.hp<=0||h.injured)return '전투 불능·중상 상태입니다.';if(combat&&h.ap<a.ap)return '행동력이 부족합니다.';if(h.focus<(a.focus||0))return '집중이 부족합니다.';if(h.gold<(a.gold||0))return '골드가 부족합니다.';if(combat&&a.attack&&h.attacked)return '이번 턴 공격 행동을 이미 사용했습니다.';if(a.mode&&h.mode!==a.mode)return a.mode+' 모드에서 사용하세요.';if(a.level&&h.level<a.level)return '아직 해금되지 않은 기술입니다.';if(a.period&&usageCount(h,a)>=usageLimit(a,sessionLimit))return '사용 횟수를 이미 소비했습니다.';return '';}
function use(h,a,combat=true,override=false,sessionLimit=1){let reason=canUse(h,a,combat,sessionLimit);if(reason&&!override)throw Error(reason);if(combat)h.ap=Math.max(0,h.ap-a.ap);h.focus=Math.max(0,h.focus-(a.focus||0));h.gold=Math.max(0,h.gold-(a.gold||0));if(combat&&a.attack)h.attacked=true;if(a.period)h.used[a.period+':'+a.id]=a.period==='session'?usageCount(h,a)+1:true;}
function damage(h,amount,reduction=0){let n=Math.max(0,amount-reduction),shield=Math.min(h.shield,n);h.shield-=shield;n-=shield;if(n>0){if(h.hp===0){h.crisis=Math.min(3,h.crisis+1);h.stable=false;if(h.crisis===3)h.injured=true;}else h.hp=Math.max(0,h.hp-n);}return {absorbed:shield,hpDamage:n};}
function heal(h,amount,data){if(h.injured)throw Error('중상은 피난처의 긴 휴식 또는 고급 치료로 해제하세요.');let actual=Math.max(0,amount-(h.statuses.some(x=>x.name==='오염')?2:0));h.hp=Math.min(maximum(h,data),h.hp+actual);if(h.hp>0){h.crisis=0;h.stable=false;}return actual;}
function levelUp(h,skill,data){if(h.level>=3)throw Error('최대 레벨입니다.');if(h.trained.includes(skill)||!data.skills.some(x=>x.name===skill))throw Error('새로운 숙련 하나를 선택해주세요.');h.level++;if(h.hp>0&&!h.injured)h.hp+=3;if(h.level===2)h.focus=Math.min(4,h.focus+1);h.trained.push(skill);}
function shortRest(h,die,data){if(h.used['expedition:short'])throw Error('이번 진입의 짧은 휴식을 이미 사용했습니다.');if(die<1||die>6)throw Error('D6 눈을 1~6으로 입력해주세요.');if(h.injured)throw Error('중상은 긴 휴식이 필요합니다.');let bonus=h.race===6&&!h.used['rest:race']?3:0;heal(h,die+h.stats['근력']+bonus,data);h.focus=Math.min(focusMax(h),h.focus+1);h.used['expedition:short']=true;if(bonus)h.used['rest:race']=true;}
function longRest(h,data){h.hp=maximum(h,data);h.focus=focusMax(h);h.shield=0;h.statuses=[];h.crisis=0;h.stable=false;h.injured=false;markReset(h,'rest');}
function newExpedition(state){if(state.party.expedition>=3)throw Error('세 번째 진입입니다. 봉쇄 해제 또는 실패 결말을 진행하세요.');state.party.expedition++;state.heroes.forEach(h=>{markReset(h,'expedition');h.inventory=h.inventory.filter(i=>!i.temporary);if(h.job===4&&slots(h)<4)h.inventory.push({id:uid(),item:'flash',free:true,temporary:true,slots:1});});}
function rollResult({die,die2,mode='normal',stat=0,trained=false,modifier=0,dc=12,attack=false}){if(!Number.isInteger(die)||die<1||die>20)throw Error('D20 눈을 1~20으로 입력해주세요.');if(mode!=='normal'&&(!Number.isInteger(die2)||die2<1||die2>20))throw Error('두 번째 D20 눈도 입력해주세요.');let face=mode==='advantage'?Math.max(die,die2):mode==='disadvantage'?Math.min(die,die2):die;let total=face+stat+(trained?2:0)+clamp(modifier,-2,2);return {face,total,critical:attack&&face===20,success:attack&&face===20?true:attack&&face===1?false:total>=dc};}
function validateState(s,data){if(!s||s.schema!==1||!Array.isArray(s.heroes)||s.heroes.length>30||s.ruleVersion!=='1.1'||!s.party||!s.combat||!Array.isArray(s.logs))throw Error('지원하지 않는 백업 파일입니다.');let ids=new Set();const num=(x,min,max)=>typeof x==='number'&&Number.isFinite(x)&&x>=min&&x<=max;for(const h of s.heroes){if(!h||typeof h.id!=='string'||ids.has(h.id)||typeof h.name!=='string'||h.name.length>60||!data.jobs[h.job]||!data.origins[h.origin]||!data.races.some(r=>r.id===h.race)||!num(h.level,1,3)||!Number.isInteger(h.level))throw Error('캐릭터 데이터가 올바르지 않습니다.');ids.add(h.id);if(!h.stats||STATS.map(k=>h.stats[k]).sort().join(',')!=='0,1,1,2,3')throw Error('능력치 데이터가 올바르지 않습니다.');if(!num(h.hp,0,maximum(h,data))||!num(h.focus,0,focusMax(h))||!num(h.luck,0,2)||!num(h.ap,0,2)||!num(h.gold,0,1e9)||!num(h.shield,0,999)||!num(h.crisis,0,3)||!Array.isArray(h.trained)||!h.trained.every(x=>data.skills.some(y=>y.name===x))||!Array.isArray(h.inventory)||h.inventory.length>8||!h.inventory.every(x=>x&&typeof x.id==='string'&&data.items.some(i=>i.id===x.item)&&[0,1].includes(x.slots))||!Array.isArray(h.statuses)||h.statuses.length>30||!h.used||typeof h.used!=='object'||Array.isArray(h.used)||!['도살','연회'].includes(h.mode)||!['light','heavy'].includes(h.armor))throw Error('자원·장비 데이터가 올바르지 않습니다.');for(const st of h.statuses){if(!st||typeof st.name!=='string'||typeof st.source!=='string'||typeof st.until!=='string')throw Error('상태 기록이 올바르지 않습니다.');}for(const k of ['gender','appearance','goal','bond','oath','weapon','originChoice'])if(typeof h[k]!=='string'||h[k].length>2000)throw Error('캐릭터 설명이 올바르지 않습니다.');}
if(s.activeId!==null&&!ids.has(s.activeId))throw Error('선택된 캐릭터가 없습니다.');let p=s.party;if(p.marathon!==undefined&&typeof p.marathon!=='boolean')throw Error('정주행 설정이 올바르지 않습니다.');if(!num(p.gold,0,1e9)||!num(p.debt,0,1e9)||!num(p.expedition,1,3)||!num(p.trust,-2,2)||!Array.isArray(p.loot)||p.loot.length>6||!p.loot.every(x=>x&&typeof x.name==='string'&&num(x.value,0,1e6))||!Array.isArray(p.chests)||!p.chests.every(x=>Number.isInteger(x)&&x>=0&&x<=4)||!Array.isArray(p.clues)||!p.clues.every(x=>typeof x==='string')||typeof p.notes!=='string')throw Error('파티 기록이 올바르지 않습니다.');if(typeof s.combat.running!=='boolean'||!num(s.combat.pattern,0,100000)||!Array.isArray(s.combat.actors)||s.combat.actors.length>60||!num(s.combat.index,0,60)||!num(s.combat.round,1,9999))throw Error('전투 기록이 올바르지 않습니다.');for(const a of s.combat.actors){if(!a||typeof a.id!=='string'||typeof a.name!=='string'||!num(a.init,-10,99)||!num(a.hp,0,1e6)||!num(a.max,1,1e6)||!num(a.ac,0,99)||!num(a.bonus,0,99)||!num(a.damage,0,999)||!['pc','enemy'].includes(a.type)||(a.type==='pc'&&!ids.has(a.heroId)))throw Error('전투 참가자 데이터가 올바르지 않습니다.');}if(s.combat.actors.length&&s.combat.index>=s.combat.actors.length)throw Error('현재 전투 차례가 범위를 벗어났습니다.');if(s.logs.length>200||!s.logs.every(x=>x&&typeof x.text==='string'&&typeof x.time==='string'))throw Error('기록 데이터가 올바르지 않습니다.');return s;}
root.Game={STATS,clamp,uid,empty,maximum,defense,focusMax,validateDraft,createHero,slots,markReset,usageCount,usageLimit,canUse,use,damage,heal,levelUp,shortRest,longRest,newExpedition,rollResult,validateState};
})(globalThis);
