'use strict';
const S=window.SyncCore,Net=window.Cloud;
const localChange=change,localPersist=persist,baseRender=render,baseUndo=handlers.undo;
let localBefore=null,appliedRecords={},incomingShared=null,sharedBusy=false,failedDraft=null,roomWorking=false;
const roomActions=new Set(['room-create','room-join','room-resume','room-leave','room-copy','room-lock','room-upload','room-refresh','room-recovery']);
navigation.splice(0,0,['room','실시간 방']);
function statusShared(){const el=$('#save-status');if(!el)return;if(Net.active)el.textContent=sharedBusy?'서버 저장 중':Net.pending?'처리 중':Net.ready?'실시간 연결됨':'서버 확인 중';if(route==='room'&&!roomWorking&&!sharedBusy&&!$('#modal').open&&!$('#main').contains(document.activeElement))render();}
function materialize(records){let board=records.board?.payload;if(!board)return null;let s=G.empty();s.party=S.clone(board.party);s.combat=S.clone(board.combat);let bad=[];for(let [id,r] of Object.entries(records)){if(r.kind!=='hero')continue;try{let one=G.empty();one.heroes=[S.clone(r.payload)];one.activeId=id;G.validateState(one,D);s.heroes.push(one.heroes[0]);}catch{bad.push(id);}}s.combat.actors=s.combat.actors.filter(a=>a.type!=='pc'||s.heroes.some(h=>h.id===a.heroId));s.combat.index=Math.min(s.combat.index,Math.max(0,s.combat.actors.length-1));if(!s.combat.actors.length)s.combat.running=false;s.activeId=s.heroes.some(h=>h.id===state.activeId)?state.activeId:(s.heroes.find(h=>records[h.id]?.ownerUid===Net.uid)?.id||s.heroes[0]?.id||null);s.logs=Net.events.map(({text,time})=>({text,time}));G.validateState(s,D);if(bad.length)toast('형식이 잘못된 캐릭터 '+bad.length+'개를 표시하지 않았습니다. GM에게 확인해주세요.');return s;}
function editingShared(){return $('#modal').open||route==='create'||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName);}
function applyIncoming(force=false){if(!Net.active||!incomingShared||sharedBusy||(!force&&editingShared()))return;try{let next=materialize(incomingShared.records);if(!next)return;state=next;appliedRecords=S.clone(incomingShared.records);incomingShared=null;history=[];gmOpen=Net.gm;render();}catch(e){Net.ready=false;toast('공유 데이터 확인 실패: '+e.message);}}
Net.onUpdate=v=>{incomingShared=v;applyIncoming();};Net.onStatus=statusShared;Net.onError=toast;
persist=function(){if(!Net.active)return localPersist();try{sessionStorage.setItem('manma-active-'+Net.code,state.activeId||'');}catch{}statusShared();};
function normalizeNewPlayer(before,after){if(Net.gm)return;let added=after.heroes.filter(h=>!before.heroes.some(x=>x.id===h.id));if(!added.length)return;if(added.length!==1||before.heroes.some(h=>appliedRecords[h.id]?.ownerUid===Net.uid))throw Error('플레이어는 방마다 자기 캐릭터 하나만 연결할 수 있습니다.');let old=added[0].id;added[0].id='pc_'+Net.uid;if(after.activeId===old)after.activeId=added[0].id;}
change=function(fn,text){if(!Net.active)return localChange(fn,text);if(sharedBusy||Net.pending){toast('서버 저장이 끝난 뒤 다시 눌러주세요.');return false;}if(!Net.ready||!navigator.onLine){toast('서버에 연결되지 않았습니다. 재연결 후 수정해주세요.');return false;}let before=S.clone(state),candidate,records=S.clone(appliedRecords);try{fn();normalizeNewPlayer(before,state);G.validateState(state,D);candidate=S.clone(state);S.plan(before,candidate,records,Net.uid,Net.gm);}catch(e){state=before;if($('#modal').open)closeModal();toast(e.message);render();return false;}
sharedBusy=true;statusShared();render();(async()=>{let committed=false;try{await Net.commit(before,candidate,records,text);committed=true;failedDraft=null;Net.ready=false;await Net.refresh();toast('서버에 저장했습니다.');}catch(e){if(committed){toast('저장은 완료됐지만 화면 갱신을 기다리고 있습니다. 재연결해주세요.');}else{failedDraft=candidate;state=before;toast('저장되지 않았습니다: '+Net.friendly(e));try{await Net.refresh();}catch{Net.ready=false;}}}finally{sharedBusy=false;applyIncoming(true);render();statusShared();}})();return true;};
handlers.undo=()=>{if(!Net.active)return baseUndo();if(sharedBusy||Net.pending)return toast('저장 완료를 기다려주세요.');if(!Net.history.length)return toast('이 기기에서 취소할 공유 변경이 없습니다.');confirmAction('내 직전 공유 변경 취소','그 이후 다른 사람이 같은 기록을 수정했다면 취소하지 않습니다. 다른 캐릭터의 변경은 유지됩니다.',async()=>{sharedBusy=true;statusShared();try{await Net.undo();await Net.refresh();toast('내 직전 변경을 취소했습니다.');}catch(e){toast(Net.friendly(e));}finally{sharedBusy=false;applyIncoming(true);render();}});};
function formatCode(c){return c?.match(/.{1,4}/g)?.join('-')||'';}
function renderRoom(){let resume=Net.resumeInfo();if(Net.active)return head('LIVE SESSION / V2.1',esc(Net.meta?.title||'TRPG의 밤'),Net.gm?'GM으로 연결되어 있습니다.':'플레이어로 연결되어 있습니다.',`${btn('최신 상태 확인','room-refresh','','quiet')}${btn('방 나가기','room-leave','','quiet')}`)+`<div class="grid two"><div class="card"><span class="pill ${Net.ready?'green':'pink'}">${sharedBusy?'서버 저장 중':Net.ready?'실시간 연결됨':'연결 확인 필요'}</span><h2 style="margin-top:16px">초대 코드</h2><p class="room-code">${formatCode(Net.code)}</p><div class="actions">${btn('코드 복사','room-copy','','primary')}${Net.gm?btn(Net.meta?.open?'새 참가자 입장 잠그기':'새 참가자 입장 허용','room-lock'):''}</div><p class="small-text">코드를 아는 사람이 참가할 수 있습니다. 초대한 사람이 모두 들어오면 입장을 잠그세요.</p></div><div class="card"><h2>참가자</h2>${Net.members.map(m=>`<div class="catalog-row"><strong>${esc(m.name)}</strong><span class="pill">${m.uid===Net.meta.gmUid?'GM':'플레이어'}${m.uid===Net.uid?' · 나':''}</span></div>`).join('')}<p class="small-text">목록은 방에 등록된 사람입니다. 현재 접속 여부를 뜻하지는 않습니다.</p></div></div><div class="card" style="margin-top:20px"><h2>내 캐릭터 연결</h2><p>${Net.gm?'GM은 모든 시트를 관리할 수 있습니다.':'자신의 캐릭터만 수정할 수 있고, 다른 캐릭터는 열람할 수 있습니다.'}</p><div class="actions">${btn('기존 기기 캐릭터 가져오기','room-upload')}${btn('새 캐릭터 만들기','room-new-character','','quiet')}<a href="#sheet">캐릭터 시트 열기</a></div><p class="small-text">방에 연결하는 캐릭터는 새 사본입니다. 기존 기기 기록은 그대로 남습니다.</p></div>${failedDraft?`<div class="notice warning">저장에 실패한 입력을 파일로 보관할 수 있습니다. 자동으로 재전송하지 않습니다. ${btn('실패한 입력 다운로드','room-recovery','','small')}</div>`:''}<div class="notice">${Net.gm?'전투·공용 기록 변경은 참가자에게 실시간으로 전달됩니다.':'공용 골드·전리품·전투 순서는 GM이 관리합니다.'} 같은 기록에 변경이 겹치면 최신 상태를 확인하고 다시 입력하세요.</div>`;
return head('LIVE SESSION / V2.1','실시간 방','초대 코드로 함께 들어와 체력과 전투 기록을 공유하세요.')+(!Net.configured()?`<div class="notice warning">공유 서버 설정이 아직 비어 있습니다. 동봉된 SETUP.md 순서대로 Firebase를 설정하면 활성화됩니다. 기존 혼자 쓰기 기능은 그대로 사용할 수 있습니다.</div>`:'')+`<div class="grid two"><div class="card"><h2>GM으로 방 만들기</h2><p class="muted">현재 기기의 캐릭터와 파티·전투 기록으로 시작합니다.</p>${btn(roomWorking?'연결 중…':'방 만들기','room-create',roomWorking?'disabled':'','primary')}</div><div class="card"><h2>플레이어로 참가</h2><p class="muted">GM에게 받은 20자리 초대 코드를 입력하세요.</p>${btn('초대 코드로 참가','room-join',roomWorking?'disabled':'')}${resume?`<div class="quick-actions">${btn('지난 방 다시 연결','room-resume',roomWorking?'disabled':'','quiet')}</div>`:''}</div></div><div class="card" style="margin-top:20px"><h2>알아두기</h2><p>로그인 화면 없이 이 브라우저의 임시 계정으로 연결합니다. 같은 기기·브라우저로 다시 들어오면 캐릭터와 GM 권한을 이어갑니다.</p><p class="muted">브라우저 데이터를 지우거나 다른 기기를 쓰면 다른 사람으로 인식됩니다. 특히 GM은 사용한 브라우저를 유지하고 전체 백업을 보관해주세요.</p><a href="#sheet">공유 없이 기존 기록으로 플레이</a></div>`;
}
render=function(){if(location.hash.slice(1)==='room'){route='room';$('#nav').innerHTML=navigation.map(([id,label],i)=>`<a href="#${id}" class="${id==='room'?'active':''}" ${id==='room'?'aria-current="page"':''}><span class="nav-num">${String(i+1).padStart(2,'0')}</span>${label}</a>`).join('');$('#main').innerHTML=renderRoom();return;}
if(Net.active&&!Net.gm&&location.hash==='#gm'){route='gm';$('#main').innerHTML=head('GAME MASTER','GM 전용 화면','현재 방의 GM만 전투와 공용 기록을 수정할 수 있습니다.')+'<a href="#party">파티 현황 보기</a>';return;}
baseRender();if(!Net.active)return;$('#main').insertAdjacentHTML('afterbegin',`<div class="live-strip"><a href="#room">${esc(Net.meta?.title||'공유 방')}</a><span>${Net.gm?'GM':'플레이어'} · ${Net.ready?'실시간 공유':'연결 확인 필요'}${sharedBusy?' · 저장 중':''}</span></div>`);
let readOnly=route==='sheet'&&hero()&&appliedRecords[hero().id]?.ownerUid!==Net.uid&&!Net.gm;if(readOnly){$('#main').insertAdjacentHTML('afterbegin','<div class="notice">다른 플레이어의 캐릭터를 보고 있습니다. 수정은 소유자 또는 GM만 할 수 있습니다.</div>');$('#main').querySelectorAll('button[data-action]').forEach(b=>{if(!['print','export-hero'].includes(b.dataset.action))b.disabled=true;});}
if(!Net.gm&&route==='party'){$('#main').querySelectorAll('button,input,textarea').forEach(b=>b.disabled=true);$('#main').querySelectorAll('[data-action="select-hero"]').forEach(b=>b.disabled=false);}
if(route==='party'){$('#main').querySelectorAll('.footnote').forEach(x=>x.textContent='이 방의 변경은 실시간으로 공유됩니다.');}
if(route==='backup'){$('#import-file').disabled=true;$('#main').querySelectorAll('[data-action="reset-all"],[data-action="storage-resume"]').forEach(x=>x.disabled=true);}
$('#main').querySelectorAll('[data-action="undo"]').forEach(b=>b.disabled=!Net.history.length||sharedBusy);statusShared();};
async function enter(task){if(roomWorking)return;roomWorking=true;localBefore=S.clone(state);try{await task();appliedRecords={};history=[];gmOpen=Net.gm;location.hash='room';try{await Net.refresh();}catch{}applyIncoming(true);}catch(e){toast(Net.friendly(e));}finally{roomWorking=false;render();}}
handlers['room-create']=()=>askForm('공유 방 만들기',input('name','방 이름','만마 TRPG의 밤','text','maxlength="60" required'),'방 만들기',v=>{enter(()=>Net.create(String(v.get('name')),state));});
handlers['room-join']=()=>askForm('초대 코드로 참가',`${input('code','초대 코드','','text','maxlength="30" required placeholder="XXXX-XXXX-XXXX-XXXX-XXXX"')}${input('name','참가자 이름','','text','maxlength="40" required')}`,'참가',v=>{let code=S.cleanCode(v.get('code'));enter(()=>Net.join(code,String(v.get('name'))));});
handlers['room-resume']=()=>{let r=Net.resumeInfo();if(!r)return;enter(async()=>{await Net.init();if(r.uid!==Net.uid)throw Error('이전 계정과 다른 브라우저 계정입니다. 초대 코드로 새로 참가하거나 GM에게 문의하세요.');await Net.join(r.code,'플레이어');});};
handlers['room-leave']=()=>{if(sharedBusy||Net.pending)return toast('서버 저장이 끝난 뒤 나가주세요.');confirmAction('방 나가기','공유 기록은 서버에 남습니다. 이 기기의 공유 전 기록으로 돌아갑니다.',()=>{Net.leave();state=localBefore||G.empty();localBefore=null;incomingShared=null;appliedRecords={};history=[];lastRoll=null;gmOpen=false;localPersist();render();});};
handlers['room-refresh']=async()=>{try{if($('#modal').open)closeModal();await Net.refresh();applyIncoming(true);toast('최신 상태를 확인했습니다.');}catch(e){toast(Net.friendly(e));}};
handlers['room-lock']=async()=>{try{await Net.lock();render();}catch(e){toast(Net.friendly(e));}};
handlers['room-copy']=()=>navigator.clipboard.writeText(formatCode(Net.code)).then(()=>toast('초대 코드를 복사했습니다.')).catch(()=>toast('복사할 수 없습니다. 표시된 코드를 직접 복사해주세요.'));
handlers['room-recovery']=()=>{if(failedDraft)download('만마_저장실패_입력백업.json',failedDraft);};
handlers['room-upload']=()=>{let hs=localBefore?.heroes||[];if(!hs.length)return toast('공유 전 기기 캐릭터가 없습니다. 새 캐릭터를 만들어주세요.');askForm('기기 캐릭터 연결',select('hero','캐릭터',hs.map(h=>({value:h.id,label:h.name})),hs[0].id),'연결',v=>change(()=>{let h=S.clone(hs.find(x=>x.id===v.get('hero')));h.id=G.uid();state.heroes.push(h);state.activeId=h.id;},'기존 캐릭터 연결'));};
handlers['room-new-character']=()=>{navTo('create');};
// Do not let a live action overwrite the local-only database or replace the room wholesale.
document.addEventListener('click',e=>{if(!Net.active)return;let b=e.target.closest('[data-action]');if(!b)return;let a=b.dataset.action;if((sharedBusy||Net.pending)&&!['export-all','export-hero','close','room-recovery'].includes(a)){e.preventDefault();e.stopImmediatePropagation();toast('서버 저장 완료를 기다려주세요.');return;}if(['reset-all','storage-resume'].includes(a)){e.preventDefault();e.stopImmediatePropagation();toast('방에서 나온 뒤 로컬 기록을 관리해주세요.');}},true);
$('#modal').addEventListener('close',()=>setTimeout(()=>applyIncoming(),0));
window.addEventListener('hashchange',()=>applyIncoming());
window.addEventListener('beforeunload',e=>{if(sharedBusy||Net.pending){e.preventDefault();e.returnValue='';}});
window.addEventListener('storage',e=>{if(Net.active&&e.key===KEY)e.stopImmediatePropagation();},true);
render();
